/* ============================================================
   شهرفرنگ — تالار گنجینه‌ی بازی‌ها (بیش از ۳۰۰ بازی معروف)
   ============================================================ */

export type PlatformId =
  | "atari2600" | "arcade" | "nes" | "snes" | "megadrive" | "gameboy"
  | "ps1" | "n64" | "ps2" | "gamecube" | "dreamcast" | "pc"
  | "msx" | "amiga" | "saturn" | "gba" | "gamegear" | "sms";

export interface Game {
  id: string;
  name: string;
  nameEn: string;
  platform: PlatformId;
  year: number;
  genre: string;
  emoji: string;
  desc: string;
  note?: string;
}

export const PLATFORMS: { id: PlatformId; fa: string; c: string }[] = [
  { id: "atari2600", fa: "آتاری ۲۶۰۰", c: "#a8552e" },
  { id: "arcade", fa: "آرکید", c: "#c2903a" },
  { id: "nes", fa: "نینتندو NES", c: "#a8431f" },
  { id: "snes", fa: "سوپر نینتندو", c: "#7c5aa2" },
  { id: "megadrive", fa: "مگا درایو", c: "#2f5d6e" },
  { id: "gameboy", fa: "گیم‌بوی", c: "#6d7448" },
  { id: "ps1", fa: "پلی‌استیشن ۱", c: "#4a6a8a" },
  { id: "n64", fa: "نینتندو ۶۴", c: "#3f7d50" },
  { id: "ps2", fa: "پلی‌استیشن ۲", c: "#31485e" },
  { id: "gamecube", fa: "گیم‌کیوب", c: "#6a4a8f" },
  { id: "dreamcast", fa: "دریم‌کست", c: "#c65c2c" },
  { id: "pc", fa: "رایانه", c: "#5c4a30" },
  { id: "msx", fa: "ام‌اس‌ایکس", c: "#8a6420" },
  { id: "amiga", fa: "آمیگا", c: "#a03a3a" },
  { id: "saturn", fa: "سگا ساترن", c: "#3a5a4a" },
  { id: "gba", fa: "گیم‌بوی ادونس", c: "#4a5a8a" },
  { id: "gamegear", fa: "گیم گیر", c: "#54423a" },
  { id: "sms", fa: "سگا مستر سیستم", c: "#4f8fd6" },
];

export const platformOf = (id: PlatformId) => PLATFORMS.find((p) => p.id === id)!;

export const GENRES = [
  "پلتفرمر", "اکشن", "ماجراجویی", "نقش‌آفرینی", "شوتر", "مبارزه‌ای",
  "مسابقه‌ای", "ورزشی", "استراتژی", "معمایی", "وحشت", "شبیه‌ساز",
];

/* ---------- کنسولِ مرتبط در گنجینه‌ی اشیاء ---------- */
export const CONSOLE_ITEM: Partial<Record<PlatformId, string>> = {
  atari2600: "atari2600",
  megadrive: "megadrive",
  gameboy: "gameboy",
  ps1: "ps1",
  n64: "nintendo-64",
  gamecube: "gamecube",
  dreamcast: "sega-dreamcast",
  gba: "gameboy-advance",
  msx: "msx",
  amiga: "amiga-500",
  saturn: "sega-saturn",
  gamegear: "sega-game-gear",
  sms: "sega-master-system",
};

export const GAMES: Game[] = [
  /* ── آرکید ── */
  { id: "pong-atc", name: "پونگ", nameEn: "PONG", platform: "arcade", year: 1972, genre: "ورزشی", emoji: "🏓", desc: "دو خط و یک نقطه؛ ساده‌ترین بازی‌ای که یک صنعت میلیاردی ساخت.", note: "نخستین دستگاه آزمایشی‌اش از انباشت سکه‌ها خراب شد." },
  { id: "space-invaders", name: "مهاجمان فضایی", nameEn: "SPACE INVADERS", platform: "arcade", year: 1978, genre: "شوتر", emoji: "👽", desc: "صف‌های فضایی که با هر شلیک تندتر می‌شدند؛ سکه‌های ژاپن را تمام کرد." },
  { id: "pacman", name: "پک‌من", nameEn: "PAC-MAN", platform: "arcade", year: 1980, genre: "معمایی", emoji: "👻", desc: "گُلبِ زردِ پرخور در هزارتو؛ از چهار روح فرار کن و همه‌چیز را بخور.", note: "نخستین شخصیتِ برند‌ساز تاریخ بازی؛ الهام‌گرفته از پیتزای گاز زده." },
  { id: "galaga", name: "گالاگا", nameEn: "GALAGA", platform: "arcade", year: 1981, genre: "شوتر", emoji: "🚀", desc: "جنگنده‌ی تنها در برابر امواج پروانه‌ای؛ نجاتِ جنگنده‌ی اسیرشده امضایش بود." },
  { id: "donkey-kong", name: "دانکی‌کنگ", nameEn: "DONKEY KONG", platform: "arcade", year: 1981, genre: "پلتفرمر", emoji: "🦍", desc: "بشقاب‌های غلتان و میمونِ بشکه‌انداز؛ نخستین ظهورِ ماریو.", note: "میاموتو در ۲۶ سالگی و با یک دعوای حقوقی بر سر کینگ‌کنگ ساختش." },
  { id: "asteroids", name: "آستروئیدز", nameEn: "ASTEROIDS", platform: "arcade", year: 1979, genre: "شوتر", emoji: "☄️", desc: "سنگ‌های فضایی و فیزیکِ لُخت؛ وکتورهای نورانیِ به‌یادماندنی." },
  { id: "centipede", name: "هزارپا", nameEn: "CENTIPEDE", platform: "arcade", year: 1981, genre: "شوتر", emoji: "🐛", desc: "هزارپایی که از سقف می‌آمد و قارچ‌ها را به مانع بدل می‌کرد." },
  { id: "defender", name: "دیفندر", nameEn: "DEFENDER", platform: "arcade", year: 1981, genre: "شوتر", emoji: "🛸", desc: "دفاع از آدم‌ربوده‌ها در دنیای بی‌پایان؛ سخت‌ترین بازی زمانش." },
  { id: "frogger", name: "قورباغه‌ی عبوری", nameEn: "FROGGER", platform: "arcade", year: 1981, genre: "معمایی", emoji: "🐸", desc: "رد شدن از بزرگ‌راه و رودخانه؛ هر عبور، یک نفسِ حبس‌شده." },
  { id: "dig-dug", name: "دیگ‌داگ", nameEn: "DIG DUG", platform: "arcade", year: 1982, genre: "معمایی", emoji: "⛏️", desc: "حفر تونل و باد کردن هیولاها؛ استراتژی در زیرِ زمین." },
  { id: "pole-position", name: "پُل پوزیشن", nameEn: "POLE POSITION", platform: "arcade", year: 1982, genre: "مسابقه‌ای", emoji: "🏎️", desc: "فرمول یکِ آرکید؛ صدای موتور و پیچ‌های پیست فوجی." },
  { id: "xevious", name: "زِویوس", nameEn: "XEVIOUS", platform: "arcade", year: 1982, genre: "شوتر", emoji: "🛩️", desc: "بمبارانِ زمینی و هوایی همزمان؛ جدّ شوترهای عمودی." },
  { id: "nineteen42", name: "نوزده‌چهل‌ودو", nameEn: "1942", platform: "arcade", year: 1984, genre: "شوتر", emoji: "✈️", desc: "جنگنده‌ی P-38 بالای اقیانوس آرام؛ سومرشدنِ شاهکارِ کپ‌کام." },
  { id: "gng-arcade", name: "شبح‌ها و جن‌ها", nameEn: "GHOSTS'N GOBLINS", platform: "arcade", year: 1985, genre: "پلتفرمر", emoji: "🛡️", desc: "شوالیه‌ای که زرهش با یک ضربه می‌پرید؛ بی‌رحم‌ترین آرکید تاریخ." },
  { id: "sf2", name: "استریت فایتر ۲", nameEn: "STREET FIGHTER II", platform: "arcade", year: 1991, genre: "مبارزه‌ای", emoji: "🥊", desc: "ریو، کن و شش مبارز دیگر؛ الفبای بازی‌های مبارزه‌ای.", note: "ترکیب‌های چنددکمه‌ای‌اش تصادفی کشف شد و بعد رسمی شد." },
  { id: "mk1", name: "مورتال کامبت", nameEn: "MORTAL KOMBAT", platform: "arcade", year: 1992, genre: "مبارزه‌ای", emoji: "🐉", desc: "فاتالیتی! خشونتی که مجلس آمریکا را به جلسه‌ی فوق‌العاده کشاند.", note: "با عکس‌برداری از بازیگران واقعی ساخته شد؛ گرافیکش «واقعی» بود." },
  { id: "nba-jam", name: "ان‌بی‌ای جَم", nameEn: "NBA JAM", platform: "arcade", year: 1993, genre: "ورزشی", emoji: "🏀", desc: "دو به دوِ دیوانه با پرش‌های سه‌متری؛ BOOMSHAKALAKA!" },
  { id: "metal-slug", name: "متال اسلاگ", nameEn: "METAL SLUG", platform: "arcade", year: 1996, genre: "شوتر", emoji: "🪖", desc: "سربازهای کوچک و انفجارهای بزرگ؛ زیباترین پیکسل‌آرتِ اکشن." },
  { id: "virtua-fighter", name: "ویرچوا فایتر", nameEn: "VIRTUA FIGHTER", platform: "arcade", year: 1993, genre: "مبارزه‌ای", emoji: "🥋", desc: "نخستین مبارزه‌ی سه‌بعدی؛ سبکِ واقع‌گرای سگای ژاپن." },
  { id: "outrun", name: "آوت‌ران", nameEn: "OUTRUN", platform: "arcade", year: 1986, genre: "مسابقه‌ای", emoji: "🏁", desc: "فراری قرمز، ساحل و موسیقی؛ تعریفِ بازیِ «حسِ خوب»." },
  { id: "double-dragon", name: "دابل دراگون", nameEn: "DOUBLE DRAGON", platform: "arcade", year: 1987, genre: "اکشن", emoji: "👊", desc: "دو برادر در خیابان‌های خراب؛ پدرِ بزن‌بهادرهای خیابانی." },
  { id: "final-fight", name: "فاینال فایت", nameEn: "FINAL FIGHT", platform: "arcade", year: 1989, genre: "اکشن", emoji: "🏙️", desc: "شهردارِ کشتی‌گیر و دخترش؛ پاک‌سازی میتران‌سیتی." },
  /* ── آتاری ۲۶۰۰ ── */
  { id: "adventure-atc", name: "ماجراجویی", nameEn: "ADVENTURE", platform: "atari2600", year: 1980, genre: "ماجراجویی", emoji: "🗺️", desc: "نخستین اکشن-ماجراجویی؛ ایستر اگِ معروفِ تاریخ اینجا پنهان شد.", note: "برنامه‌نویسش نامش را در اتاقی مخفی نوشت؛ نخستین ایستر اگ." },
  { id: "pitfall", name: "پیت‌فال!", nameEn: "PITFALL!", platform: "atari2600", year: 1982, genre: "پلتفرمر", emoji: "🌴", desc: "تاب خوردن روی تمساح‌ها؛ چهار میلیون فروش روی یک کنسول." },
  { id: "yars-revenge", name: "انتقام یار", nameEn: "YARS' REVENGE", platform: "atari2600", year: 1982, genre: "شوتر", emoji: "🪰", desc: "مگس‌های فضایی و سپر رنگین‌کمانی؛ پرفروش‌ترین اورجینالِ آتاری." },
  { id: "river-raid", name: "رودخانه‌ی رید", nameEn: "RIVER RAID", platform: "atari2600", year: 1982, genre: "شوتر", emoji: "✈️", desc: "پرواز روی رود و مدیریت سوخت؛ اعتیادِ سوخت‌گیری.", note: "سازنده‌اش کارول شا، از نخستین زنان برنامه‌نویس بازی." },
  { id: "kaboom", name: "کابوم!", nameEn: "KABOOM!", platform: "atari2600", year: 1981, genre: "معمایی", emoji: "💣", desc: "سطل‌ها را بگیر! بمب‌های دیوانه‌ی دزدِ خندان." },
  { id: "enduro", name: "اندورو", nameEn: "ENDURO", platform: "atari2600", year: 1983, genre: "مسابقه‌ای", emoji: "🚗", desc: "مسابقه‌ی شبانه‌روز؛ برف و مه پشت فرمانِ پیکسلی." },
  { id: "keystone", name: "کیستون کیپرز", nameEn: "KEYSTONE KAPERS", platform: "atari2600", year: 1983, genre: "اکشن", emoji: "🚔", desc: "دزد و پلیس روی خط آهن؛ پلیسِ سبیلوی معروفِ آتاری." },
  { id: "hero-2600", name: "هیرو", nameEn: "H.E.R.O.", platform: "atari2600", year: 1984, genre: "اکشن", emoji: "🚁", desc: "کوله‌جِت و دینامیت؛ نجات معدنچیان از اعماق زمین." },
  { id: "combat", name: "نبرد", nameEn: "COMBAT", platform: "atari2600", year: 1977, genre: "اکشن", emoji: "🎖️", desc: "بازیِ همراه کنسول؛ تانک‌های پیکسلیِ دونفره‌ی حیاط‌ها." },
  { id: "breakout", name: "بریک‌اوت", nameEn: "BREAKOUT", platform: "atari2600", year: 1978, genre: "معمایی", emoji: "🧱", desc: "شکستن دیوار آجرها؛ کاری که جابز و وزنیاک را معروف کرد." },
  { id: "et-2600", name: "ئی‌تی", nameEn: "E.T. THE EXTRA-TERRESTRIAL", platform: "atari2600", year: 1982, genre: "ماجراجویی", emoji: "👽", desc: "بازی‌ای که آن‌قدر بد بود میلیون‌ها کارتریجش را دفن کردند.", note: "در پنج هفته ساخته شد؛ لاشه‌هایش در ۲۰۱۴ از بیابان نیومکزیکو بیرون آمد." },
  /* ── نینتندو NES ── */
  { id: "smb", name: "سوپر ماریو برادران", nameEn: "SUPER MARIO BROS", platform: "nes", year: 1985, genre: "پلتفرمر", emoji: "🍄", desc: "لوله‌کشی که قارچ می‌خورد و پرنسس نجات می‌دهد؛ نجات‌دهنده‌ی صنعت بازی.", note: "۴۰ میلیون نسخه؛ تقریباً همراه هر سه NES یکی فروخته شد." },
  { id: "smb3", name: "سوپر ماریو برادران ۳", nameEn: "SUPER MARIO BROS 3", platform: "nes", year: 1988, genre: "پلتفرمر", emoji: "🦝", desc: "نقشه‌ی جهان، کُستوم راکون و هشت پادشاهی؛ اوجِ هنرِ پیکسلی NES." },
  { id: "zelda1", name: "افسانه‌ی زلدا", nameEn: "THE LEGEND OF ZELDA", platform: "nes", year: 1986, genre: "ماجراجویی", emoji: "🗡️", desc: "هایرول، مثلث قدرت و کارتریج طلایی؛ پدرِ اکشن-ماجراجویی‌ها.", note: "نخستین کارتریج با باتریِ ذخیره؛ دنیایش الهام از غارهای کودکی میاموتو بود." },
  { id: "metroid1", name: "متروید", nameEn: "METROID", platform: "nes", year: 1986, genre: "ماجراجویی", emoji: "🪐", desc: "ساموس آران در سیاره‌ی زبس؛ تنهایی و اکتشاف به تمام معنا." },
  { id: "megaman2", name: "مگامن ۲", nameEn: "MEGA MAN 2", platform: "nes", year: 1988, genre: "پلتفرمر", emoji: "🤖", desc: "هشت ربات‌استاد و قلعه‌ی وایلی؛ موسیقی‌اش هنوز زنده است." },
  { id: "castlevania1", name: "کسلوانیا", nameEn: "CASTLEVANIA", platform: "nes", year: 1986, genre: "پلتفرمر", emoji: "🦇", desc: "شلاقِ خانوادگیِ بلمونت در قلعه‌ی دراکولا؛ شلاق بزن، بالا برو." },
  { id: "contra1", name: "کونترا", nameEn: "CONTRA", platform: "nes", year: 1988, genre: "شوتر", emoji: "🔫", desc: "دو کماندو، هزار تیر؛ کدِ کونامی و سی جانِ همیشگی.", note: "«بالا بالا پایین پایین چپ راست چپ راست B A»؛ معروف‌ترین کد تقلب تاریخ." },
  { id: "excitebike", name: "اکسایت‌بایک", nameEn: "EXCITEBIKE", platform: "nes", year: 1984, genre: "مسابقه‌ای", emoji: "🏍️", desc: "موتورسواری روی گل و موانع؛ پیست‌سازش جلوتر از زمانش بود." },
  { id: "ice-climber", name: "یخ‌نورد", nameEn: "ICE CLIMBER", platform: "nes", year: 1985, genre: "پلتفرمر", emoji: "🧊", desc: "دو خواهر و برادر با چکش؛ بالا رفتن بی‌پایان از کوه یخی." },
  { id: "duck-hunt", name: "شکار اردک", nameEn: "DUCK HUNT", platform: "nes", year: 1984, genre: "شوتر", emoji: "🦆", desc: "تفنگ نوری و سگِ خندان؛ انتقامِ سگ وقتی خطا می‌زدی!" },
  { id: "ninja-gaiden", name: "نینجا گایدن", nameEn: "NINJA GAIDEN", platform: "nes", year: 1988, genre: "اکشن", emoji: "🥷", desc: "ریو هایابوسا و کات‌سین‌های پیکسلی؛ اکشنی با قصه‌ی جدی." },
  { id: "battletoads", name: "بتل‌تودز", nameEn: "BATTLETOADS", platform: "nes", year: 1991, genre: "اکشن", emoji: "🐸", desc: "قورباغه‌های بدنساز؛ مرحله‌ی سرعتِ Turbo Tunnel کابوس بود." },
  { id: "kirby-adventure", name: "ماجراجویی کربی", nameEn: "KIRBY'S ADVENTURE", platform: "nes", year: 1993, genre: "پلتفرمر", emoji: "🌸", desc: "توپِ صورتیِ مکنده؛ NES در اواخر عمرش این‌همه خوشگل نبود!" },
  { id: "blaster-master", name: "بلاستر مستر", nameEn: "BLASTER MASTER", platform: "nes", year: 1988, genre: "اکشن", emoji: "🚙", desc: "جیسون و تانک سوفیا؛ پیاده زیرِ زمین، سواره رویش." },
  { id: "gng-nes", name: "شبح‌ها و جن‌ها (NES)", nameEn: "GHOSTS'N GOBLINS (NES)", platform: "nes", year: 1986, genre: "پلتفرمر", emoji: "⚰️", desc: "آرتور و زره‌ی فداکار؛ دو بار تمام کردنش برای پایان واقعی." },
  { id: "gradius", name: "گرادیوس", nameEn: "GRADIUS", platform: "nes", year: 1986, genre: "شوتر", emoji: "🛸", desc: "ویک وایپر و نوار قدرتِ گزینه‌ها؛ شوترِ استراتژیک کونامی." },
  { id: "bionic-commando", name: "بیونیک کماندو", nameEn: "BIONIC COMMANDO", platform: "nes", year: 1988, genre: "پلتفرمر", emoji: "🪝", desc: "بدون پرش! فقط بازوی قلابی؛ قانونی که همه‌چیز را عوض کرد." },
  { id: "punch-out", name: "پانچ‌اوت!!", nameEn: "PUNCH-OUT!!", platform: "nes", year: 1987, genre: "ورزشی", emoji: "🥊", desc: "لیتل مک در برابر مایک تایسون؛ الگوها را حفظ کن، جاخالی بده." },
  { id: "river-city", name: "ریور سیتی رنسوم", nameEn: "RIVER CITY RANSOM", platform: "nes", year: 1989, genre: "اکشن", emoji: "🍜", desc: "دو دانش‌آموز در شهرِ اوباش؛ با خرید دونات قوی‌تر شو!" },
  { id: "chip-n-dale", name: "چیپ و دیل", nameEn: "CHIP 'N DALE RESCUE RANGERS", platform: "nes", year: 1990, genre: "پلتفرمر", emoji: "🐿️", desc: "سنجاب‌های نجات‌بخش؛ جعبه پرت کن و رفیقت را بغل کن!" },
  { id: "ducktales", name: "داک‌تیلز", nameEn: "DUCKTALES", platform: "nes", year: 1989, genre: "پلتفرمر", emoji: "🦆", desc: "اسکروج با عصای فنری‌اش؛ ماه را هم در نقشه‌ها می‌گشت." },
  { id: "darkwing-duck", name: "دارک‌وینگ داک", nameEn: "DARKWING DUCK", platform: "nes", year: 1992, genre: "پلتفرمر", emoji: "🦇", desc: "«من تروری هستم که شب پرواز می‌کند!»؛ مگامن‌وار با اردک." },
  { id: "zelda2", name: "ماجراجویی زلدا", nameEn: "ZELDA II: THE ADVENTURE OF LINK", platform: "nes", year: 1987, genre: "نقش‌آفرینی", emoji: "🏰", desc: "نمای پهلو و امتیاز تجربه؛ جسورترین زلدای تاریخ." },
  { id: "kid-icarus", name: "کید ایکاروس", nameEn: "KID ICARUS", platform: "nes", year: 1986, genre: "پلتفرمر", emoji: "🏹", desc: "پیت و کمانِ نورانی؛ اسطوره‌ی یونانی با قلبِ ژاپنی." },
  { id: "bomberman", name: "بمبرمن", nameEn: "BOMBERMAN", platform: "nes", year: 1985, genre: "معمایی", emoji: "💥", desc: "بمب بچین و راه باز کن؛ دونفره‌اش دعواهای خواهر و برادری بود." },
  { id: "battle-city", name: "بتل سیتی", nameEn: "BATTLE CITY", platform: "nes", year: 1985, genre: "شوتر", emoji: "🛡️", desc: "تاتانک‌ها! از عقابِ خانه دفاع کن؛ نقشه‌سازش افسانه بود." },
  { id: "tetris-nes", name: "تتریس (NES)", nameEn: "TETRIS (NES)", platform: "nes", year: 1989, genre: "معمایی", emoji: "🧩", desc: "تندتر می‌شود، همیشه تندتر؛ موسیقیِ کوروبشینکا در مغزت می‌ماند." },
  { id: "double-dragon-2", name: "دابل دراگون ۲", nameEn: "DOUBLE DRAGON II", platform: "nes", year: 1989, genre: "اکشن", emoji: "🥋", desc: "انتقام ماریان؛ ضربات زانویی که همه بلد بودند." },
  { id: "faxanadu", name: "فاکسانادو", nameEn: "FAXANADU", platform: "nes", year: 1987, genre: "نقش‌آفرینی", emoji: "🌳", desc: "دنیای درونِ درختِ عظیم؛ اتمسفری‌ترین نقش‌آفرینی NES." },
  { id: "rygar", name: "رایگار", nameEn: "RYGAR", platform: "nes", year: 1987, genre: "پلتفرمر", emoji: "🪓", desc: "جنگجوی زره‌پوش با دیسکِ چرخان؛ دنیای بازِ جلوتر از زمان." },
  { id: "megaman3", name: "مگامن ۳", nameEn: "MEGA MAN 3", platform: "nes", year: 1990, genre: "پلتفرمر", emoji: "🐕", desc: "راشِ سگِ ربات و پروتومنِ مرموز؛ اسلاید آمد، سرعت آمد." },
  { id: "super-c", name: "سوپر سی", nameEn: "SUPER C", platform: "nes", year: 1990, genre: "شوتر", emoji: "🧬", desc: "بیگانه‌ها برگشتند؛ کونترای عمودی با سقف‌های تنگ." },
  { id: "life-force", name: "لایف فورس", nameEn: "LIFE FORCE", platform: "nes", year: 1988, genre: "شوتر", emoji: "🦠", desc: "پرواز در بدنِ یک موجود زنده؛ گرادیوسِ ترسناک." },
  { id: "rad-racer", name: "رَد ریسر", nameEn: "RAD RACER", platform: "nes", year: 1987, genre: "مسابقه‌ای", emoji: "🏁", desc: "با عینک سه‌بعدیِ مقوایی! مسابقه‌ی ساحلی اسکوارانوشی." },
  /* ── سوپر نینتندو ── */
  { id: "smw", name: "سوپر ماریو ورلد", nameEn: "SUPER MARIO WORLD", platform: "snes", year: 1990, genre: "پلتفرمر", emoji: "🎈", desc: "یوشی آمد؛ ۹۶ خروجی و جزیره‌ی دایناسورها.", note: "با SNES عرضه شد و ۲۰ میلیون فروخت؛ مخفی‌ترین رازهای تاریخ پلتفرمر." },
  { id: "yoshis-island", name: "جزیره‌ی یوشی", nameEn: "YOSHI'S ISLAND", platform: "snes", year: 1995, genre: "پلتفرمر", emoji: "🥚", desc: "نقاشیِ مدادشمعی؛ بیبی‌ماریو روی پشتِ یوشی گریه می‌کند." },
  { id: "alttp", name: "زلدا: پیوند به گذشته", nameEn: "ZELDA: A LINK TO THE PAST", platform: "snes", year: 1991, genre: "ماجراجویی", emoji: "🌗", desc: "دو جهانِ روشن و تاریک؛ الگوی همه‌ی زلداهای بعدی." },
  { id: "super-metroid", name: "سوپر متروید", nameEn: "SUPER METROID", platform: "snes", year: 1994, genre: "ماجراجویی", emoji: "🛡️", desc: "زبسِ ساکت و وحشتناک؛ اتمسفری که هنوز معیار است." },
  { id: "chrono-trigger", name: "کرونو تریگر", nameEn: "CHRONO TRIGGER", platform: "snes", year: 1995, genre: "نقش‌آفرینی", emoji: "⏳", desc: "سفر در زمان با ۱۳ پایان؛ رویای مشترک سازندگان فاینال فانتزی و دراگون کوئست.", note: "میاموتو روی جلدش نقاشی کشید؛ اغلب بهترین RPG تاریخ خوانده می‌شود." },
  { id: "ff6", name: "فاینال فانتزی ۶", nameEn: "FINAL FANTASY VI", platform: "snes", year: 1994, genre: "نقش‌آفرینی", emoji: "🎭", desc: "چهارده قهرمان و اپرای مشهور؛ شرورِ واقعی، کفکا بود." },
  { id: "sf2-turbo", name: "استریت فایتر ۲ توربو", nameEn: "STREET FIGHTER II TURBO", platform: "snes", year: 1993, genre: "مبارزه‌ای", emoji: "🔥", desc: "سرعتِ دیوانه و شوریوکن‌های آتشین؛ پرفروش‌ترین بازی مستقل SNES." },
  { id: "dkc1", name: "دانکی‌کنگ کانتری", nameEn: "DONKEY KONG COUNTRY", platform: "snes", year: 1994, genre: "پلتفرمر", emoji: "🍌", desc: "گرافیک پیش‌رندرِ «سیلیکون گرافیکس» که همه را میخکوب کرد." },
  { id: "dkc2", name: "دانکی‌کنگ کانتری ۲", nameEn: "DONKEY KONG COUNTRY 2", platform: "snes", year: 1995, genre: "پلتفرمر", emoji: "🏴‍☠️", desc: "دیدی و دیکسی در جزیره‌ی دزدان؛ موسیقی‌اش جادو بود." },
  { id: "dkc3", name: "دانکی‌کنگ کانتری ۳", nameEn: "DONKEY KONG COUNTRY 3", platform: "snes", year: 1996, genre: "پلتفرمر", emoji: "❄️", desc: "شمالِ برفی و کایاس؛ آخرِ سه‌گانه‌ی طلایی رِر." },
  { id: "earthbound", name: "ارث‌باوند", nameEn: "EARTHBOUND", platform: "snes", year: 1994, genre: "نقش‌آفرینی", emoji: "🧢", desc: "نس در شهرِ مدرن با چوب بیسبال؛ عجیب‌ترین RPG تاریخ." },
  { id: "secret-of-mana", name: "راز مانا", nameEn: "SECRET OF MANA", platform: "snes", year: 1993, genre: "نقش‌آفرینی", emoji: "🌿", desc: "اکشن-نقش‌آفرینیِ سه‌نفره‌ی همزمان؛ درخت مانا صدا می‌زند." },
  { id: "starfox", name: "استارفاکس", nameEn: "STAR FOX", platform: "snes", year: 1993, genre: "شوتر", emoji: "🦊", desc: "روینگ‌های سه‌بعدی با چیپ Super FX؛ جادوی ریاضیِ آرگونایت." },
  { id: "fzero", name: "اف-زیرو", nameEn: "F-ZERO", platform: "snes", year: 1990, genre: "مسابقه‌ای", emoji: "🏎️", desc: "ماشین‌های شناورِ Mode 7؛ کاپیتان فالکن و ۵۰۰ کیلومتر سرعت." },
  { id: "super-mario-kart", name: "سوپر ماریو کارت", nameEn: "SUPER MARIO KART", platform: "snes", year: 1992, genre: "مسابقه‌ای", emoji: "🍌", desc: "پوست موز جلوی رفیق؛ تولدِ ژانرِ کارت-ریسینگ.", note: "پوست موز و پوسته‌ی قرمز، دوستی‌های زیادی را خراب کرد!" },
  { id: "megamanx", name: "مگامن ایکس", nameEn: "MEGA MAN X", platform: "snes", year: 1993, genre: "پلتفرمر", emoji: "🤖", desc: "ایکس، زیرو و سگما؛ مگامنِ بالنده‌ی جدی‌تر و سریع‌تر." },
  { id: "rock-n-roll", name: "راک اند رول ریسینگ", nameEn: "ROCK N' ROLL RACING", platform: "snes", year: 1993, genre: "مسابقه‌ای", emoji: "🎸", desc: "مسابقه با موشک و مین، روی موسیقی بلک‌سبث؛ «لری هافمن!»" },
  { id: "sunset-riders", name: "سانست رایدرز", nameEn: "SUNSET RIDERS", platform: "snes", year: 1993, genre: "شوتر", emoji: "🤠", desc: "چهار هفت‌تیرکش؛ «Bury me with my money!»" },
  { id: "zombies-ate", name: "زامبی‌ها همسایه‌ام را خوردند", nameEn: "ZOMBIES ATE MY NEIGHBORS", platform: "snes", year: 1993, genre: "شوتر", emoji: "🧟", desc: "طنزِ ترسناکِ لوکاس‌آرتز؛ جاروبرقی‌ات را بردار و بیا." },
  { id: "super-castlevania4", name: "سوپر کسلوانیا ۴", nameEn: "SUPER CASTLEVANIA IV", platform: "snes", year: 1991, genre: "پلتفرمر", emoji: "⛓️", desc: "شلاقِ چرخانِ سیمون؛ قلعه با Mode 7 می‌چرخید!" },
  { id: "actraiser", name: "اکت‌رایزر", nameEn: "ACTRAISER", platform: "snes", year: 1990, genre: "شبیه‌ساز", emoji: "⚡", desc: "نیمی خدا و شهرساز، نیمی جنگجو؛ ایده‌ای که تکرار نشد." },
  { id: "illusion-of-gaia", name: "توهم گایا", nameEn: "ILLUSION OF GAIA", platform: "snes", year: 1993, genre: "نقش‌آفرینی", emoji: "🗿", desc: "ویل و تمدن‌های گمشده؛ اکشن-ماجراجوییِ کوئینتت." },
  { id: "terranigma", name: "ترانیگما", nameEn: "TERRANIGMA", platform: "snes", year: 1995, genre: "نقش‌آفرینی", emoji: "🌋", desc: "زمین را دوباره خلق کن؛ پایان‌بندی‌اش هنوز دل می‌شکافد." },
  { id: "killer-instinct", name: "کیلر اینستینکت", nameEn: "KILLER INSTINCT", platform: "snes", year: 1994, genre: "مبارزه‌ای", emoji: "🦖", desc: "C-C-C-COMBO BREAKER! رندر دیجیتال و ریتمِ تند." },
  { id: "super-punchout", name: "سوپر پانچ‌اوت!!", nameEn: "SUPER PUNCH-OUT!!", platform: "snes", year: 1994, genre: "ورزشی", emoji: "🥊", desc: "لیتل مک برگشت؛ مشت‌های مخصوص و حریف‌های کاریکاتوری." },
  { id: "nba-jam-te", name: "ان‌بی‌ای جَم (SNES)", nameEn: "NBA JAM T.E.", platform: "snes", year: 1994, genre: "ورزشی", emoji: "🏀", desc: "توربو تایم! سلتیک و بولزِ دو نفره روی مبل." },
  { id: "iss-snes", name: "اینترنشنال سوپراستار ساکر", nameEn: "INTERNATIONAL SUPERSTAR SOCCER", platform: "snes", year: 1994, genre: "ورزشی", emoji: "⚽", desc: "آلگان و ربرتو؛ فوتبالی که نسل ما باهاش دعوا می‌کرد.", note: "«آلگان» در واقع فاوستینو آسپرییا بود؛ نام‌ها شوخیِ مترجمان بود." },
  { id: "aladdin-snes", name: "علاءالدین (SNES)", nameEn: "ALADDIN (SNES)", platform: "snes", year: 1993, genre: "پلتفرمر", emoji: "🧞", desc: "کپ‌کام؛ انیمیشن دیزنی با ظرافتِ پیکسلِ ژاپنی." },
  { id: "lionking-snes", name: "شیرشاه (SNES)", nameEn: "THE LION KING (SNES)", platform: "snes", year: 1994, genre: "پلتفرمر", emoji: "🦁", desc: "وست‌وود؛ از «I Just Can't Wait» تا سیمبای بزرگسال." },
  { id: "ogre-battle", name: "اوگر بتل", nameEn: "OGRE BATTLE", platform: "snes", year: 1993, genre: "استراتژی", emoji: "🃏", desc: "کارت تاروت و نبردِ همزمان؛ استراتژیِ عظیمِ کوئست." },
  { id: "tactics-ogre", name: "تکتیکس اوگر", nameEn: "TACTICS OGRE", platform: "snes", year: 1995, genre: "استراتژی", emoji: "♟️", desc: "انتخاب‌های اخلاقیِ سنگین؛ پدرِ استراتژی‌های نوبتی مدرن." },
  { id: "harvest-moon", name: "هاروست مون", nameEn: "HARVEST MOON", platform: "snes", year: 1996, genre: "شبیه‌ساز", emoji: "🌾", desc: "مزرعه‌ی پدربزرگ را آباد کن؛ تولدِ ژانرِ مزرعه‌داری." },
  /* ── مگا درایو ── */
  { id: "sonic1", name: "سونیک ۱", nameEn: "SONIC THE HEDGEHOG", platform: "megadrive", year: 1991, genre: "پلتفرمر", emoji: "🦔", desc: "جوجه‌تیغی آبی با سرعتِ صوت؛ جوابِ تندِ سگا به ماریو." },
  { id: "sonic2", name: "سونیک ۲", nameEn: "SONIC THE HEDGEHOG 2", platform: "megadrive", year: 1992, genre: "پلتفرمر", emoji: "🦔", desc: "تیلز آمد، چرخشِ اسپین‌دَش آمد؛ روزِ جهانیِ سونیک." },
  { id: "sonic3k", name: "سونیک ۳ و ناکلز", nameEn: "SONIC 3 & KNUCLES", platform: "megadrive", year: 1994, genre: "پلتفرمر", emoji: "💍", desc: "دو کارتریجِ قفل‌شو؛ بزرگ‌ترین ماجراجوییِ کلاسیک سونیک." },
  { id: "sor1", name: "شورش در شهر", nameEn: "STREETS OF RAGE", platform: "megadrive", year: 1991, genre: "اکشن", emoji: "👊", desc: "سه پلیسِ سابق در شهرِ فاسد؛ موسیقیِ یوزو کوشیرو افسانه است." },
  { id: "sor2", name: "شورش در شهر ۲", nameEn: "STREETS OF RAGE 2", platform: "megadrive", year: 1992, genre: "اکشن", emoji: "🥊", desc: "اسکیت و مکس؛ بهترین بزن‌بهادرِ ۱۶ بیتی از نظر خیلی‌ها." },
  { id: "sor3", name: "شورش در شهر ۳", nameEn: "STREETS OF RAGE 3", platform: "megadrive", year: 1994, genre: "اکشن", emoji: "🦾", desc: "ربات‌ها و کانگورو؛ پایانِ سه‌گانه‌ی طلایی سگا." },
  { id: "golden-axe", name: "تبر طلایی", nameEn: "GOLDEN AXE", platform: "megadrive", year: 1989, genre: "اکشن", emoji: "🪓", desc: "بربر، آمازون و کوتوله؛ فانتزیِ کلاسیکِ سگا." },
  { id: "altered-beast", name: "آلترد بیست", nameEn: "ALTERED BEAST", platform: "megadrive", year: 1988, genre: "اکشن", emoji: "🐺", desc: "«Rise from your grave!»؛ گرگینه‌ی بازیِ همراه مگا درایو." },
  { id: "phantasy4", name: "فانتاسی استار ۴", nameEn: "PHANTASY STAR IV", platform: "megadrive", year: 1993, genre: "نقش‌آفرینی", emoji: "🌌", desc: "علمی‌تخیلی با کمیک‌های میان‌پرده؛ اوجِ RPG سگا." },
  { id: "shining2", name: "شینینگ فورس ۲", nameEn: "SHINING FORCE II", platform: "megadrive", year: 1993, genre: "استراتژی", emoji: "⚔️", desc: "استراتژی نوبتیِ فانتزی؛ شطرنج با شمشیر و جادو." },
  { id: "gunstar", name: "گان‌استار هیروز", nameEn: "GUNSTAR HEROES", platform: "megadrive", year: 1993, genre: "شوتر", emoji: "💥", desc: "تِرژر! اسلحه‌ی ترکیبی و اکشنی که نفس نمی‌کشد." },
  { id: "comix-zone", name: "کمیکس زون", nameEn: "COMIX ZONE", platform: "megadrive", year: 1995, genre: "اکشن", emoji: "💬", desc: "داخلِ صفحاتِ کمیک گیر افتادی؛ پنل به پنل جلو برو." },
  { id: "ecco", name: "اکو دلفین", nameEn: "ECCO THE DOLPHIN", platform: "megadrive", year: 1992, genre: "ماجراجویی", emoji: "🐬", desc: "دلفین و بیگانگانِ زیرِ دریا؛ زیبا، سخت و غمگین." },
  { id: "vectorman", name: "وکتورمن", nameEn: "VECTORMAN", platform: "megadrive", year: 1995, genre: "شوتر", emoji: "🤖", desc: "رباتِ پیش‌رندر؛ نمایش قدرتِ مگا درایو در آخرِ عمرش." },
  { id: "ristar", name: "ریستار", nameEn: "RISTAR", platform: "megadrive", year: 1995, genre: "پلتفرمر", emoji: "⭐", desc: "ستاره‌ای با دست‌های کشسان؛ گوهرِ دیرکشفِ سگا." },
  { id: "toejam", name: "توجَم و ارل", nameEn: "TOEJAM & EARL", platform: "megadrive", year: 1991, genre: "ماجراجویی", emoji: "🎧", desc: "دو فضاییِ هیپ‌هاپ؛ نقشه‌های تصادفی و فانک." },
  { id: "bloodlines", name: "کسلوانیا: خون‌بس", nameEn: "CASTLEVANIA: BLOODLINES", platform: "megadrive", year: 1994, genre: "پلتفرمر", emoji: "🩸", desc: "کسلوانیا در اروپای جنگ جهانی؛ نیزه و شلاق." },
  { id: "rocket-knight", name: "راکت نایت ادونچرز", nameEn: "ROCKET KNIGHT ADVENTURES", platform: "megadrive", year: 1993, genre: "پلتفرمر", emoji: "🚀", desc: "موشِ شوالیه با جت‌پک؛ شاهکارِ فراموش‌شده‌ی کونامی." },
  { id: "landstalker", name: "لنداستالکر", nameEn: "LANDSTALKER", platform: "megadrive", year: 1992, genre: "ماجراجویی", emoji: "🗺️", desc: "اکشن-ماجراجوییِ ایزومتریک؛ زلدای مگا درایو." },
  { id: "shinobi3", name: "شینوبی ۳", nameEn: "SHINOBI III", platform: "megadrive", year: 1993, genre: "اکشن", emoji: "🥷", desc: "جو موساشی در اوجِ هنر؛ نینجایی که می‌دوید و می‌درخشید." },
  { id: "dynamite-headdy", name: "دینامیت هدی", nameEn: "DYNAMITE HEADDY", platform: "megadrive", year: 1994, genre: "پلتفرمر", emoji: "🎪", desc: "سرِ جداشونده‌ی تِرژر؛ دیوانه‌ترین پلتفرمرِ سگا." },
  { id: "earthworm-jim", name: "کرم خاکی جیم", nameEn: "EARTHWORM JIM", platform: "megadrive", year: 1994, genre: "پلتفرمر", emoji: "🪱", desc: "کرمی با کت و شلوارِ ابرقهرمانی؛ طنزِ محضِ شینی." },
  { id: "aladdin-md", name: "علاءالدین (مگا درایو)", nameEn: "ALADDIN (GENESIS)", platform: "megadrive", year: 1993, genre: "پلتفرمر", emoji: "🪔", desc: "ویرجین؛ انیمیشنِ دیزی که با دست کشیده شد." },
  { id: "nhl94", name: "ان‌اچ‌ال ۹۴", nameEn: "NHL '94", platform: "megadrive", year: 1993, genre: "ورزشی", emoji: "🏒", desc: "یک‌دکمه‌ای که هنوز بهترین ورزشی دونفره خوانده می‌شود." },
  /* ── گیم‌بوی ── */
  { id: "tetris-gb", name: "تتریس (گیم‌بوی)", nameEn: "TETRIS (GAME BOY)", platform: "gameboy", year: 1989, genre: "معمایی", emoji: "🧩", desc: "بسته‌ی همراهِ گیم‌بوی؛ اعتیادآورترین ازدواجِ تاریخ بازی.", note: "حقوقش در یک جنگ سردِ حقوقیِ جهانی بین شوروی و غرب حل شد." },
  { id: "pokemon-red", name: "پوکمون قرمز/آبی", nameEn: "POKÉMON RED / BLUE", platform: "gameboy", year: 1996, genre: "نقش‌آفرینی", emoji: "⚡", desc: "همه را بگیر! ۱۵۱ پوکمون و کابلِ اتصال؛ پدیده‌ی جهانی.", note: "پرفروش‌ترین RPG تاریخ؛ «Pika!» یک فرهنگ ساخت." },
  { id: "pokemon-yellow", name: "پوکمون زرد", nameEn: "POKÉMON YELLOW", platform: "gameboy", year: 1998, genre: "نقش‌آفرینی", emoji: "🐭", desc: "پیکاچو پشتِ سرت راه می‌رود؛ نسخه‌ی کارتون." },
  { id: "pokemon-gold", name: "پوکمون طلا/نقره", nameEn: "POKÉMON GOLD / SILVER", platform: "gameboy", year: 1999, genre: "نقش‌آفرینی", emoji: "🥇", desc: "چرخه‌ی شب و روز؛ ۱۰۰ پوکمونِ جدید و دو منطقه." },
  { id: "mland1", name: "سوپر ماریو لند", nameEn: "SUPER MARIO LAND", platform: "gameboy", year: 1989, genre: "پلتفرمر", emoji: "🐢", desc: "ماریوی جیبی در ساراسالند؛ ساده اما دوست‌داشتنی." },
  { id: "mland2", name: "سوپر ماریو لند ۲", nameEn: "SUPER MARIO LAND 2", platform: "gameboy", year: 1992, genre: "پلتفرمر", emoji: "🥕", desc: "نخستین ظهورِ واریو؛ قلعه‌ی شش در." },
  { id: "links-awakening", name: "زلدا: بیداری لینک", nameEn: "ZELDA: LINK'S AWAKENING", platform: "gameboy", year: 1993, genre: "ماجراجویی", emoji: "🐟", desc: "جزیره‌ی رؤیاییِ کوهولینت؛ زلدایی بدون هایرول و مثلث." },
  { id: "metroid2", name: "متروید ۲", nameEn: "METROID II", platform: "gameboy", year: 1991, genre: "ماجراجویی", emoji: "🕸️", desc: "شکار مترویدها در SR388؛ تاریک‌ترین مأموریت ساموس." },
  { id: "kirby-dreamland", name: "سرزمین رؤیای کربی", nameEn: "KIRBY'S DREAM LAND", platform: "gameboy", year: 1992, genre: "پلتفرمر", emoji: "⭐", desc: "نخستین بازی ساکورایی؛ توپِ صورتی هنوز مکنده نمی‌شد." },
  { id: "wario-land", name: "واریو لند", nameEn: "WARIO LAND", platform: "gameboy", year: 1994, genre: "پلتفرمر", emoji: "🧄", desc: "ضدقهرمانِ طمع‌کار؛ مردن برایش شروعِ دوباره بود." },
  { id: "dr-mario", name: "دکتر ماریو", nameEn: "DR. MARIO", platform: "gameboy", year: 1990, genre: "معمایی", emoji: "💊", desc: "قرص‌ها را بچرخان و ویروس‌ها را پاک کن؛ پازلِ پزشکی." },
  { id: "megamanv", name: "مگامن ۵ (GB)", nameEn: "MEGA MAN V (GB)", platform: "gameboy", year: 1994, genre: "پلتفرمر", emoji: "🌌", desc: "رباتهایی از منظومه‌ی شمسی؛ مگامنِ فضایی." },
  { id: "batman-gb", name: "بتمن (گیم‌بوی)", nameEn: "BATMAN: RETURN OF THE JOKER", platform: "gameboy", year: 1991, genre: "پلتفرمر", emoji: "🃏", desc: "شوالیه‌ی تاریک در جیب؛ سخت‌تر از چیزی که فکر می‌کنی." },
  { id: "dk-land", name: "دانکی‌کنگ لند", nameEn: "DONKEY KONG LAND", platform: "gameboy", year: 1995, genre: "پلتفرمر", emoji: "🍌", desc: "DKC در ۴ رنگِ سبز؛ معجزه‌ی فشرده‌سازی." },
  { id: "harvest-gb", name: "هاروست مون (GB)", nameEn: "HARVEST MOON GB", platform: "gameboy", year: 1997, genre: "شبیه‌ساز", emoji: "🐄", desc: "مزرعه‌داریِ جیبی؛ بذر بکار، گاو بچران، دل ببند." },
  /* ── پلی‌استیشن ۱ ── */
  { id: "ff7", name: "فاینال فانتزی ۷", nameEn: "FINAL FANTASY VII", platform: "ps1", year: 1997, genre: "نقش‌آفرینی", emoji: "🌠", desc: "کلاد، ایروث و سفرُس؛ RPG ژاپنی دنیا را گرفت.", note: "مرگ ایروث هنوز بحث‌برانگیزترین لحظه‌ی تاریخ بازی است." },
  { id: "ff8", name: "فاینال فانتزی ۸", nameEn: "FINAL FANTASY VIII", platform: "ps1", year: 1999, genre: "نقش‌آفرینی", emoji: "🦅", desc: "اسکوال و رینوا؛ عشقِ نوجوانانه با گرافیکِ پیش‌رندر." },
  { id: "ff9", name: "فاینال فانتزی ۹", nameEn: "FINAL FANTASY IX", platform: "ps1", year: 2000, genre: "نقش‌آفرینی", emoji: "🎻", desc: "بازگشت به ریشه‌های فانتزی؛ وداعِ باشکوه PS1." },
  { id: "mgs1", name: "متال گیر سالید", nameEn: "METAL GEAR SOLID", platform: "ps1", year: 1998, genre: "اکشن", emoji: "📦", desc: "اسنیک در سایه‌ی رکس؛ سینمای تعاملیِ کوجیما.", note: "نبرد سایکو منتیس با خواندنِ ذهن، کارتریج را هم می‌خواند!" },
  { id: "re1", name: "رزیدنت ایول", nameEn: "RESIDENT EVIL", platform: "ps1", year: 1996, genre: "وحشت", emoji: "🧟", desc: "عمارت اسپنسر؛ «Jill sandwich!» و تولدِ سروایول-هارور." },
  { id: "re2", name: "رزیدنت ایول ۲", nameEn: "RESIDENT EVIL 2", platform: "ps1", year: 1998, genre: "وحشت", emoji: "👮", desc: "لیان و کلر در راکون‌سیتی؛ دو دیسک، دو قصه." },
  { id: "re3", name: "رزیدنت ایول ۳: نمسیس", nameEn: "RESIDENT EVIL 3: NEMESIS", platform: "ps1", year: 1999, genre: "وحشت", emoji: "🚁", desc: "«S.T.A.R.S!»؛ ترسی که دنبال‌تان می‌دود." },
  { id: "crash1", name: "کرش بندیکوت", nameEn: "CRASH BANDICOOT", platform: "ps1", year: 1996, genre: "پلتفرمر", emoji: "🦊", desc: "کیسه‌داری که می‌چرخد؛ نقابِ سونی در برابر ماریو." },
  { id: "crash2", name: "کرش بندیکوت ۲", nameEn: "CRASH BANDICOOT 2", platform: "ps1", year: 1997, genre: "پلتفرمر", emoji: "💎", desc: "کورسِ نیتروس؛ بزرگ‌تر، شلوغ‌تر، بهتر." },
  { id: "crash3", name: "کرش بندیکوت ۳", nameEn: "CRASH BANDICOOT: WARPED", platform: "ps1", year: 1998, genre: "پلتفرمر", emoji: "🕰️", desc: "سفر در زمان با موتور و هواپیما؛ اوجِ ناتی‌داگ." },
  { id: "spyro1", name: "اسپایرو", nameEn: "SPYRO THE DRAGON", platform: "ps1", year: 1998, genre: "پلتفرمر", emoji: "🐲", desc: "اژدهای بنفشِ کوچولو؛ جمع‌آوری جواهر و پرواز." },
  { id: "spyro2", name: "اسپایرو ۲", nameEn: "SPYRO 2: Ripto'S RAGE", platform: "ps1", year: 1999, genre: "پلتفرمر", emoji: "🔥", desc: "ریپتو در ساحل‌های آفتابی؛ دنیاهای بازِ کوچک." },
  { id: "tekken3", name: "تکن ۳", nameEn: "TEKKEN 3", platform: "ps1", year: 1997, genre: "مبارزه‌ای", emoji: "🥊", desc: "جین کازاما؛ عمق و روانی‌ای که هنوز معیار است." },
  { id: "gt1", name: "گرن توریسمو", nameEn: "GRAN TURISMO", platform: "ps1", year: 1997, genre: "مسابقه‌ای", emoji: "🏁", desc: "«شبیه‌سازِ رانندگی واقعی»؛ گواهینامه بگیر، ماشین بخر." },
  { id: "gt2", name: "گرن توریسمو ۲", nameEn: "GRAN TURISMO 2", platform: "ps1", year: 1999, genre: "مسابقه‌ای", emoji: "🚗", desc: "۶۰۰ ماشین، دو دیسک؛ دایره‌المعارفِ خودرو." },
  { id: "tomb1", name: "توم رایدر", nameEn: "TOMB RAIDER", platform: "ps1", year: 1996, genre: "ماجراجویی", emoji: "🏺", desc: "لارا کرافت در مقبره‌های مصر؛ پلتفرمرِ سه‌بعدیِ جدی." },
  { id: "sh1", name: "سایلنت هیل", nameEn: "SILENT HILL", platform: "ps1", year: 1999, genre: "وحشت", emoji: "🌫️", desc: "شهری زیرِ مه؛ ترسِ روانی که خشونت نمی‌خواست." },
  { id: "sotn", name: "کسلوانیا: سمفونی شب", nameEn: "CASTLEVANIA: SOTN", platform: "ps1", year: 1997, genre: "نقش‌آفرینی", emoji: "🦇", desc: "الوکارد، قلعه‌ی وارونه و صد‌ها سلاح؛ تولدِ «مترویدوانیا».", note: "نصفه‌ی دوم قلعه وارونه است؛ شاهکارِ مخفی‌کاری." },
  { id: "chrono-cross", name: "کرونو کراس", nameEn: "CHRONO CROSS", platform: "ps1", year: 1999, genre: "نقش‌آفرینی", emoji: "🌀", desc: "دو جهانِ موازی؛ ۴۵ شخصیت و موسیقیِ مسحورکننده." },
  { id: "vagrant-story", name: "واگِرانت استوری", nameEn: "VAGRANT STORY", platform: "ps1", year: 2000, genre: "نقش‌آفرینی", emoji: "🗡️", desc: "لئاس و شهرِ نفرین‌شده؛ هنری‌ترین RPG نسل ۳۲ بیتی." },
  { id: "thps2", name: "تونی هاوک ۲", nameEn: "TONY HAWK'S PRO SKATER 2", platform: "ps1", year: 2000, genre: "ورزشی", emoji: "🛹", desc: "کمبو و موسیقیِ پانک؛ اعتیادِ یک‌دقیقه‌ایِ همیشگی." },
  { id: "wipeout", name: "وایپ‌اوت", nameEn: "WIPEOUT", platform: "ps1", year: 1995, genre: "مسابقه‌ای", emoji: "🛸", desc: "ضدجاذبه با تکنو؛ PS1 با این بازی «باکلاس» شد." },
  { id: "ridge-racer", name: "ریج ریسر", nameEn: "RIDGE RACER", platform: "ps1", year: 1994, genre: "مسابقه‌ای", emoji: "🏎️", desc: "دریفتِ آرکید؛ بازیِ همراهِ لانچ PS1 و نامکو." },
  { id: "nfs3", name: "نید فور اسپید ۳", nameEn: "NEED FOR SPEED III", platform: "ps1", year: 1998, genre: "مسابقه‌ای", emoji: "🚓", desc: "فرار از پلیس؛ تعقیب‌وگریزِ واقعیِ جاده‌ها." },
  { id: "twisted-metal2", name: "توئیستد متال ۲", nameEn: "TWISTED METAL 2", platform: "ps1", year: 1996, genre: "مسابقه‌ای", emoji: "🤡", desc: "ماشین‌های جنگی در شهر؛ کلونِ دیوانه و مینِی‌من." },
  { id: "syphon-filter", name: "سایفون فیلتر", nameEn: "SYPHON FILTER", platform: "ps1", year: 1999, genre: "شوتر", emoji: "🕶️", desc: "گیب لوگان و ویروسِ سایفون؛ جاسوسیِ تمام‌عیار." },
  { id: "medievil", name: "مدی‌ایول", nameEn: "MEDIEVIL", platform: "ps1", year: 1998, genre: "اکشن", emoji: "💀", desc: "شوالیه‌ی اسکلتیِ سر دنیل؛ طنزِ گوتیکِ بریتانیایی." },
  { id: "ape-escape", name: "ایپ اسکِیپ", nameEn: "APE ESCAPE", platform: "ps1", year: 1999, genre: "پلتفرمر", emoji: "🐵", desc: "میمون‌های فراری با استیکِ آنالوگ؛ نوآوریِ خالص." },
  { id: "klonoa", name: "کلونوآ", nameEn: "KLONOA", platform: "ps1", year: 1997, genre: "پلتفرمر", emoji: "💨", desc: "دو‌و‌نیم‌بعدیِ لطیف؛ گریه‌ی پایانش معروف است." },
  { id: "oddworld", name: "آدورلد: آدیسی ابی", nameEn: "ODDWORLD: ABE'S ODDYSEE", platform: "ps1", year: 1997, genre: "پلتفرمر", emoji: "🟢", desc: "فرار از کشتارگاه؛ پازل-پلتفرمرِ سیاسی و تاریک." },
  { id: "dino-crisis", name: "داینو کرایسیس", nameEn: "DINO CRISISIS", platform: "ps1", year: 1999, genre: "وحشت", emoji: "🦖", desc: "رزیدنت ایول با دایناسور؛ رجینا در جزیره‌ی ترس." },
  { id: "parasite-eve", name: "پارازایت ایو", nameEn: "PARASITE EVE", platform: "ps1", year: 1998, genre: "نقش‌آفرینی", emoji: "🔬", desc: "آیا بریا و میتوکندریِ شورشی؛ RPG-وحشتِ اسکوار." },
  { id: "soul-reaver", name: "لگاسی آف کاین: سول ریور", nameEn: "LEGACY OF KAIN: SOUL REAVER", platform: "ps1", year: 1999, genre: "ماجراجویی", emoji: "🗡️", desc: "رازایلِ خون‌آشام؛ جهش بین بُعدِ ماده و روح." },
  { id: "gta1-ps", name: "جی‌تی‌ای", nameEn: "GRAND THEFT AUTO", platform: "ps1", year: 1997, genre: "اکشن", emoji: "🚕", desc: "شهرِ آزاد از نمای بالا؛ جنجالی که امپراتوری شد." },
  { id: "driver1", name: "درایور", nameEn: "DRIVER", platform: "ps1", year: 1999, genre: "مسابقه‌ای", emoji: "🚔", desc: "تانر، پلیسِ نفوذی؛ شهرهای واقعی و مأموریت‌های تعقیب." },
  { id: "isspro", name: "وینینگ الون", nameEn: "ISS PRO EVOLUTION", platform: "ps1", year: 1999, genre: "ورزشی", emoji: "⚽", desc: "کونامی؛ فوتبالی که بالاخره «واقعی» شد." },
  { id: "ace-combat2", name: "ایس کامبت ۲", nameEn: "ACE COMBAT 2", platform: "ps1", year: 1997, genre: "شوتر", emoji: "✈️", desc: "جنگنده‌های خیالی؛ آسمانِ آرکیدِ نامکو." },
  { id: "soul-blade", name: "سول بلید", nameEn: "SOUL BLADE", platform: "ps1", year: 1996, genre: "مبارزه‌ای", emoji: "⚔️", desc: "مبارزه‌ی سلاح‌به‌سلاحِ سه‌بعدی؛ جدّ سول‌کالیبر." },
  /* ── نینتندو ۶۴ ── */
  { id: "sm64", name: "سوپر ماریو ۶۴", nameEn: "SUPER MARIO 64", platform: "n64", year: 1996, genre: "پلتفرمر", emoji: "🍄", desc: "تصاویرِ سه‌بعدی آزاد شد؛ دوربین و پرشِ سه‌بعدی اینجا تعریف شد.", note: "درهای قلعه و ۱۲۰ ستاره؛ هنوز معیار طراحی جهان‌باز است." },
  { id: "oot", name: "زلدا: اوکارینا تایم", nameEn: "ZELDA: OCARINA OF TIME", platform: "n64", year: 1998, genre: "ماجراجویی", emoji: "🎵", desc: "شاهزاده‌ی زمان؛ Z-targeting و معابدِ بی‌نقص.", note: "در Metacritic با امتیاز ۹۹، بهترین بازی تاریخ است." },
  { id: "majoras-mask", name: "زلدا: نقاب ماجورا", nameEn: "ZELDA: MAJORA'S MASK", platform: "n64", year: 2000, genre: "ماجراجویی", emoji: "🌙", desc: "سه روز تا سقوط ماه؛ تاریک‌ترین و عجیب‌ترین زلدا." },
  { id: "mk64", name: "ماریو کارت ۶۴", nameEn: "MARIO KART 64", platform: "n64", year: 1996, genre: "مسابقه‌ای", emoji: "🍌", desc: "چهار نفره روی یک مبل؛ پوست‌موزِ سه‌بعدی!" },
  { id: "goldeneye", name: "گلدن‌آی ۰۰۷", nameEn: "GOLDENEYE 007", platform: "n64", year: 1997, genre: "شوتر", emoji: "🕴️", desc: "شوترِ کنسولیِ جدی شد؛ اسلیر مپِ ابدی.", note: "چهار نفره‌ی صفحه‌چهارتکه‌اش سال‌ها استاندارد شوترِ مبل بود." },
  { id: "perfect-dark", name: "پرفکت دارک", nameEn: "PERFECT DARK", platform: "n64", year: 2000, genre: "شوتر", emoji: "👩‍✈️", desc: "جوانا دارک؛ گلدن‌آیِ بزرگ‌تر و عجیب‌تر." },
  { id: "banjo1", name: "بانجو-کازویی", nameEn: "BANJO-KAZOOIE", platform: "n64", year: 1998, genre: "پلتفرمر", emoji: "🐻", desc: "خرس و پرنده؛ جمع‌آوریِ ریز و درشت در کوهستان جادو." },
  { id: "banjo2", name: "بانجو-تویی", nameEn: "BANJO-TOOIE", platform: "n64", year: 2000, genre: "پلتفرمر", emoji: "🎒", desc: "کوله‌پشتی‌های جادویی؛ بزرگ‌تر و جسورتر." },
  { id: "starfox64", name: "استارفاکس ۶۴", nameEn: "STAR FOX 64", platform: "n64", year: 1997, genre: "شوتر", emoji: "🦊", desc: "«Do a barrel roll!»؛ رینگ‌ویپ و لرزشِ کنترلر." },
  { id: "fzerox", name: "اف-زیرو ایکس", nameEn: "F-ZERO X", platform: "n64", year: 1998, genre: "مسابقه‌ای", emoji: "🏎️", desc: "۳۰ ماشین همزمان با ۶۰ فریم؛ سرعتِ محض." },
  { id: "wave-race", name: "ویو ریس ۶۴", nameEn: "WAVE RACE 64", platform: "n64", year: 1996, genre: "مسابقه‌ای", emoji: "🚤", desc: "جِت‌اسکی روی موج‌های واقعیِ فیزیک؛ گوینده‌ی مسابقه فراموش‌نشدنی." },
  { id: "mario-party1", name: "ماریو پارتی", nameEn: "MARIO PARTY", platform: "n64", year: 1998, genre: "معمایی", emoji: "🎲", desc: "تاس بریز، مینی‌گیم، دعوا کن؛ دوستی‌ها همین‌جا تمام می‌شد." },
  { id: "smash64", name: "سوپر اسمش برادرز", nameEn: "SUPER SMASH BROS", platform: "n64", year: 1999, genre: "مبارزه‌ای", emoji: "🥊", desc: "ستاره‌های نینتندو در یک رینگ؛ پرتابشان کن بیرون!" },
  { id: "paper-mario", name: "پیپر ماریو", nameEn: "PAPER MARIO", platform: "n64", year: 2000, genre: "نقش‌آفرینی", emoji: "📄", desc: "ماریوی کاغذی؛ RPG لطیف با طنزِ عالی." },
  { id: "dk-racing", name: "دیدی کونگ ریسینگ", nameEn: "DIDDY KONG RACING", platform: "n64", year: 1997, genre: "مسابقه‌ای", emoji: "🛩️", desc: "مسابقه با ماشین، هاورکرافت و هواپیما؛ جواهرِ رِر." },
  { id: "dk64", name: "دانکی‌کنگ ۶۴", nameEn: "DONKEY KONG 64", platform: "n64", year: 1999, genre: "پلتفرمر", emoji: "🍌", desc: "پنج میمون، دویست موز؛ بزرگ‌ترین جمع‌آوریِ نسل." },
  { id: "turok1", name: "توراک", nameEn: "TUROK: DINOSAUR HUNTER", platform: "n64", year: 1997, genre: "شوتر", emoji: "🦖", desc: "شکارچی دایناسور؛ شوترِ اول‌شخصِ بومیِ N64." },
  { id: "conker", name: "کانکرز بد فور دی", nameEn: "CONKER'S BAD FUR DAY", platform: "n64", year: 2001, genre: "پلتفرمر", emoji: "🐿️", desc: "سنجابِ بزرگسال؛ طنز سیاه روی کنسولِ بچه‌ها!" },
  { id: "pilotwings", name: "پایلوت‌وینگز ۶۴", nameEn: "PILOTWINGS 64", platform: "n64", year: 1996, genre: "شبیه‌ساز", emoji: "🪂", desc: "پرواز بر فراز جزایر؛ آرامشِ خالصِ N64." },
  { id: "yoshis-story", name: "قصه‌ی یوشی", nameEn: "YOSHI'S STORY", platform: "n64", year: 1997, genre: "پلتفرمر", emoji: "🍉", desc: "کتابِ مصورِ سه‌بعدی؛ «هپی!» خوردنِ میوه‌ها." },
  { id: "rogue-squadron", name: "استار وارز: روگ اسکادران", nameEn: "STAR WARS: ROGUE SQUADRON", platform: "n64", year: 1998, genre: "شوتر", emoji: "🛸", desc: "ایکس‌وینگ بر فراز هاث؛ موسیقیِ جان ویلیامز." },
  { id: "snowboarding", name: "۱۰۸۰ اسنوبردینگ", nameEn: "1080° SNOWBOARDING", platform: "n64", year: 1998, genre: "ورزشی", emoji: "🏂", desc: "برفِ براق و فیزیکِ واقعی؛ حسِ سرما از تلویزیون می‌آمد." },
  /* ── پلی‌استیشن ۲ ── */
  { id: "gta3", name: "جی‌تی‌ای ۳", nameEn: "GTA III", platform: "ps2", year: 2001, genre: "اکشن", emoji: "🌉", desc: "لیبرتی‌سیتیِ سه‌بعدی؛ جهانِ بازِ مدرن اینجا شروع شد." },
  { id: "gtavc", name: "جی‌تی‌ای: وایس سیتی", nameEn: "GTA: VICE CITY", platform: "ps2", year: 2002, genre: "اکشن", emoji: "🌴", desc: "میامیِ دهه‌ی هشتاد با رادیوی فلش‌اف‌ام؛ تامی ورستی." },
  { id: "gtasa", name: "جی‌تی‌ای: سن آندریاس", nameEn: "GTA: SAN ANDREAS", platform: "ps2", year: 2004, genre: "اکشن", emoji: "🚲", desc: "سی‌جی در سه شهر؛ بزرگ‌ترین نقشه‌ی نسل.", note: "«Ah shit, here we go again»؛ پرفروش‌ترین بازی PS2." },
  { id: "gow1", name: "گاد آو وار", nameEn: "GOD OF WAR", platform: "ps2", year: 2005, genre: "اکشن", emoji: "⚔️", desc: "کراتوس و خشمِ المپ؛ تیغ‌های زنجیری." },
  { id: "gow2", name: "گاد آو وار ۲", nameEn: "GOD OF WAR II", platform: "ps2", year: 2007, genre: "اکشن", emoji: "🔥", desc: "انتقام از زئوس؛ PS2 در آخرین نفس‌هایش غرید." },
  { id: "sotc", name: "شَدو آو د کولوسوس", nameEn: "SHADOW OF THE COLOSSUS", platform: "ps2", year: 2005, genre: "ماجراجویی", emoji: "🗿", desc: "شانزده غول و یک عشق؛ هنرِ سکوتِ اُوئدا.", note: "هر غول یک معبدِ متحرک؛ فقط ۱۶ نبرد، همه فراموش‌نشدنی." },
  { id: "ico", name: "ایکو", nameEn: "ICO", platform: "ps2", year: 2001, genre: "ماجراجویی", emoji: "🤝", desc: "پسرِ شاخ‌دار، دستِ یوردا را بگیر؛ قصه‌ای بی‌کلام." },
  { id: "mgs2", name: "متال گیر سالید ۲", nameEn: "METAL GEAR SOLID 2", platform: "ps2", year: 2001, genre: "اکشن", emoji: "🎖️", desc: "تانکر و بیگ‌شِل؛ بازی‌ای که با مخاطبش بازی کرد." },
  { id: "mgs3", name: "متال گیر سالید ۳", nameEn: "METAL GEAR SOLID 3", platform: "ps2", year: 2004, genre: "اکشن", emoji: "🐍", desc: "اسنیک باس در جنگل؛ بقا، استتار و بوس." },
  { id: "dmc1", name: "دویل می کرای", nameEn: "DEVIL MAY CRY", platform: "ps2", year: 2001, genre: "اکشن", emoji: "😈", desc: "دانته و شمشیر و تیر؛ «استایلیش!»" },
  { id: "dmc3", name: "دویل می کرای ۳", nameEn: "DEVIL MAY CRY 3", platform: "ps2", year: 2005, genre: "اکشن", emoji: "🗡️", desc: "جوانیِ دانته و ویرژیل؛ اوجِ اکشنِ استایلیش." },
  { id: "re4", name: "رزیدنت ایول ۴", nameEn: "RESIDENT EVIL 4", platform: "ps2", year: 2005, genre: "وحشت", emoji: "🪓", desc: "لیان در روستای اسپانیا؛ دوربینِ روی شانه‌ای که ژانر را عوض کرد." },
  { id: "ffx", name: "فاینال فانتزی ۱۰", nameEn: "FINAL FANTASY X", platform: "ps2", year: 2001, genre: "نقش‌آفرینی", emoji: "🌊", desc: "تیدوس و یونا در اسپیرا؛ بلیتس‌بال و وداعِ گریه‌دار." },
  { id: "ffxii", name: "فاینال فانتزی ۱۲", nameEn: "FINAL FANTASY XII", platform: "ps2", year: 2006, genre: "نقش‌آفرینی", emoji: "🏜️", desc: "ایوالیسِ سیاسی؛ گامبیت‌ها و نبردِ بی‌درز." },
  { id: "kh1", name: "کینگدام هارتس", nameEn: "KINGDOM HEARTS", platform: "ps2", year: 2002, genre: "نقش‌آفرینی", emoji: "🗝️", desc: "سورا، میکی و دیزنی؛ عجیب‌ترین ازدواجِ بازی و انیمیشن." },
  { id: "kh2", name: "کینگدام هارتس ۲", nameEn: "KINGDOM HEARTS II", platform: "ps2", year: 2005, genre: "نقش‌آفرینی", emoji: "✨", desc: "سازمان ۱۳؛ اکشنِ روان و موسیقیِ شیمومورا." },
  { id: "okami", name: "اوکامی", nameEn: "OKAMI", platform: "ps2", year: 2006, genre: "ماجراجویی", emoji: "🐺", desc: "آmaterاسو، الهه‌ی گرگ؛ نقاشی با قلمِ آسمانی.", note: "گرافیکِ آبرنگی‌اش شبیه طومارهای ژاپنی است؛ بی‌زمان." },
  { id: "katamari", name: "کاتاماری داماسی", nameEn: "KATAMARI DAMACY", platform: "ps2", year: 2004, genre: "معمایی", emoji: "🌀", desc: "گلوله‌ی چسبناکِ همه‌چیزخوار؛ عجیب‌ترین ایده‌ی نسل." },
  { id: "jak1", name: "جک و دکستر", nameEn: "JAK AND DAXTER", platform: "ps2", year: 2001, genre: "پلتفرمر", emoji: "🦦", desc: "ناتی‌داگِ پس از کرش؛ اکو و ماجراجوییِ رنگی." },
  { id: "ratchet1", name: "رچت و کلنک", nameEn: "RATCHET & CLANK", platform: "ps2", year: 2002, genre: "پلتفرمر", emoji: "🔧", desc: "آچارِ همه‌فن‌حریف؛ سلاح‌های دیوانه‌تر از خودِ بازی." },
  { id: "sly1", name: "اسلای کوپر", nameEn: "SLY COOPER", platform: "ps2", year: 2002, genre: "پلتفرمر", emoji: "🦝", desc: "راکونِ دزدِ نجیب‌زاده؛ مخفی‌کاریِ کارتونی." },
  { id: "gt3", name: "گرن توریسمو ۳", nameEn: "GRAN TURISMO 3", platform: "ps2", year: 2001, genre: "مسابقه‌ای", emoji: "🏎️", desc: "نمایشِ قدرتِ PS2؛ گرافیکی که همه را میخکوب کرد." },
  { id: "gt4", name: "گرن توریسمو ۴", nameEn: "GRAN TURISMO 4", platform: "ps2", year: 2004, genre: "مسابقه‌ای", emoji: "🚙", desc: "۷۰۰ ماشین؛ حالت عکاسی‌اش مدرسه‌ی ماشین‌بازی بود." },
  { id: "nfsu", name: "نید فور اسپید: آندرگراوند", nameEn: "NFS: UNDERGROUND", platform: "ps2", year: 2003, genre: "مسابقه‌ای", emoji: "🌃", desc: "تیونینگِ شبانه؛ نئون و «Get Low»." },
  { id: "nfsmw", name: "نید فور اسپید: موست وانتد", nameEn: "NFS: MOST WANTED", platform: "ps2", year: 2005, genre: "مسابقه‌ای", emoji: "🚔", desc: "فرار از بلک‌لیست؛ BMW و پلیسِ سیرا ویو." },
  { id: "burnout3", name: "برن‌اوت ۳: تیک‌داون", nameEn: "BURNOUT 3: TAKEDOWN", platform: "ps2", year: 2004, genre: "مسابقه‌ای", emoji: "💥", desc: "تیک‌داون کن! صحنه‌های آهسته‌ی تصادف، جایزه‌ی بازی." },
  { id: "tekken5", name: "تکن ۵", nameEn: "TEKKEN 5", platform: "ps2", year: 2004, genre: "مبارزه‌ای", emoji: "🥋", desc: "جینپاچی و برج؛ روان‌ترین تکنِ سه‌بعدی." },
  { id: "sc3", name: "سول‌کالیبر ۳", nameEn: "SOULCALIBUR III", platform: "ps2", year: 2005, genre: "مبارزه‌ای", emoji: "⚔️", desc: "شمشیرِ روح؛ زیباترین مبارزه‌ی سلاح‌بازان." },
  { id: "pes6", name: "پرو اولوشن ساکر ۶", nameEn: "PRO EVOLUTION SOCCER 6", platform: "ps2", year: 2006, genre: "ورزشی", emoji: "⚽", desc: "«Adriano و شوت ۹۹!»؛ افسانه‌ی فوتبالِ کافه‌نت‌ها.", note: "شوتِ آدریانو از وسط زمین، دروازه‌بان را با توپ داخل می‌برد." },
  { id: "bully", name: "بولی", nameEn: "BULLY", platform: "ps2", year: 2006, genre: "اکشن", emoji: "🎒", desc: "جیمی در مدرسه‌ی بول‌ورث؛ جی‌تی‌ایِ حیاط مدرسه." },
  { id: "pop-sot", name: "شاهزاده‌ی ایران: شن‌های زمان", nameEn: "PRINCE OF PERSIA: SOT", platform: "ps2", year: 2003, genre: "ماجراجویی", emoji: "⏳", desc: "خنجر و شنِ زمان؛ «برگردان زمان را!»" },
  { id: "sh2", name: "سایلنت هیل ۲", nameEn: "SILENT HILL 2", platform: "ps2", year: 2001, genre: "وحشت", emoji: "🔺", desc: "جیمز و شهرِ گناه؛ عمیق‌ترین ترسِ روانیِ تاریخ.", note: "هر هیولا آینه‌ی ذهنِ جیمز است؛ هرم‌هد برای همیشه ماند." },
  /* ── گیم‌کیوب ── */
  { id: "melee", name: "سوپر اسمش برادرز میلی", nameEn: "SUPER SMASH BROS MELEE", platform: "gamecube", year: 2001, genre: "مبارزه‌ای", emoji: "⚡", desc: "سرعت و تکنیک؛ هنوز بعد از دو دهه تورنمنت دارد." },
  { id: "wind-waker", name: "زلدا: ویند ویکر", nameEn: "ZELDA: THE WIND WAKER", platform: "gamecube", year: 2002, genre: "ماجراجویی", emoji: "⛵", desc: "دریای سل‌شید و قایقِ قرمز؛ جسورترین زلدا." },
  { id: "twilight", name: "زلدا: تویلایت پرنسس", nameEn: "ZELDA: TWILIGHT PRINCESS", platform: "gamecube", year: 2006, genre: "ماجراجویی", emoji: "🐺", desc: "لینکِ گرگینه؛ دنیای تاریکِ نسلِ بعد." },
  { id: "metroid-prime1", name: "متروید پرایم", nameEn: "METROID PRIME", platform: "gamecube", year: 2002, genre: "شوتر", emoji: "🪐", desc: "اول‌شخصِ اکتشافی؛ اسکنر و تنهاییِ تالون." },
  { id: "metroid-prime2", name: "متروید پرایم ۲", nameEn: "METROID PRIME 2: ECHOES", platform: "gamecube", year: 2004, genre: "شوتر", emoji: "🌗", desc: "دنیای روشن و تاریکِ آتر؛ تاریک‌ترین پرایم." },
  { id: "re-remake", name: "رزیدنت ایول (بازسازی)", nameEn: "RESIDENT EVIL REMAKE", platform: "gamecube", year: 2002, genre: "وحشت", emoji: "🏚️", desc: "عمارت اسپنسر دوباره؛ بازسازی‌ای که معیار شد." },
  { id: "pikmin1", name: "پیکمین", nameEn: "PIKMIN", platform: "gamecube", year: 2001, genre: "استراتژی", emoji: "🌱", desc: "موجودات گیاهیِ فرمان‌بردار؛ باغبانیِ استراتژیک میاموتو." },
  { id: "pikmin2", name: "پیکمین ۲", nameEn: "PIKMIN 2", platform: "gamecube", year: 2004, genre: "استراتژی", emoji: "🍄", desc: "گنج‌یابیِ زیرزمینی؛ دو فرمانده و بدهیِ شرکت." },
  { id: "mkdd", name: "ماریو کارت: دبل دش!!", nameEn: "MARIO KART: DOUBLE DASH!!", platform: "gamecube", year: 2003, genre: "مسابقه‌ای", emoji: "🎈", desc: "دو سرنشین، یک کارت؛ ایتم‌های اختصاصیِ زوج‌ها." },
  { id: "ttyd", name: "پیپر ماریو: هزار در", nameEn: "PAPER MARIO: THE THOUSAND-YEAR DOOR", platform: "gamecube", year: 2004, genre: "نقش‌آفرینی", emoji: "🚪", desc: "شهر کاغذیِ روگ‌پورت؛ RPG با شخصیت‌های بی‌نقص." },
  { id: "luigis-mansion", name: "عمارت لوئیجی", nameEn: "LUIGI'S MANSION", platform: "gamecube", year: 2001, genre: "ماجراجویی", emoji: "👻", desc: "جاروبرقیِ ارواح؛ لوئیجی بالاخره قهرمانِ خودش بود." },
  { id: "animal-crossing", name: "انیمال کراسینگ", nameEn: "ANIMAL CROSSING", platform: "gamecube", year: 2001, genre: "شبیه‌ساز", emoji: "🍃", desc: "روستای حیوانات؛ ساعتِ واقعی و بدهی به تنوکی." },
  { id: "mario-sunshine", name: "سوپر ماریو سان‌شاین", nameEn: "SUPER MARIO SUNSHINE", platform: "gamecube", year: 2002, genre: "پلتفرمر", emoji: "☀️", desc: "جزیره‌ی دلفین و فِلدِ آب‌پاش؛ تمیز کن و بپر!" },
  /* ── دریم‌کست ── */
  { id: "shenmue1", name: "شنموی", nameEn: "SHENMUE", platform: "dreamcast", year: 1999, genre: "ماجراجویی", emoji: "🥋", desc: "ریو و آینه‌ی اژدها؛ دنیای زنده‌ای که جلوتر از زمانش بود.", note: "گران‌ترین بازی زمان خودش؛ «FREE» یعنی سرگرمیِ کامل." },
  { id: "shenmue2", name: "شنموی ۲", nameEn: "SHENMUE II", platform: "dreamcast", year: 2001, genre: "ماجراجویی", emoji: "🏮", desc: "کوچه‌های هنگ‌کنگ؛ قصه‌ای که ۱۸ سال معطل ماند." },
  { id: "soulcalibur1", name: "سول‌کالیبر", nameEn: "SOULCALIBUR", platform: "dreamcast", year: 1999, genre: "مبارزه‌ای", emoji: "🗡️", desc: "زیباترین مبارزه‌ی لانچ تاریخ؛ شمشیرِ روح می‌درخشد." },
  { id: "crazy-taxi", name: "کریزی تاکسی", nameEn: "CRAZY TAXI", platform: "dreamcast", year: 1999, genre: "مسابقه‌ای", emoji: "🚕", desc: "مسافر ببر، زمان بساز؛ «Way to go!» با آف‌اسپرینگ." },
  { id: "jet-set-radio", name: "جت ست رادیو", nameEn: "JET SET RADIO", platform: "dreamcast", year: 2000, genre: "اکشن", emoji: "🛼", desc: "گرافیتی با اسپری؛ سل‌شیدِ پیشگام و هیپ‌هاپ." },
  { id: "virtua-tennis", name: "ویرچوا تنیس", nameEn: "VIRTUA TENNIS", platform: "dreamcast", year: 1999, genre: "ورزشی", emoji: "🎾", desc: "تنیسِ آرکید؛ ساده به‌نظر می‌آید، استادانه است." },
  { id: "skies", name: "اسکایز آو آرکیدیا", nameEn: "SKIES OF ARCADIA", platform: "dreamcast", year: 2000, genre: "نقش‌آفرینی", emoji: "🎈", desc: "کشتی‌های پرنده و دریای ابر؛ ماجراجوییِ خالص." },
  { id: "grandia2", name: "گراندیا ۲", nameEn: "GRANDIA II", platform: "dreamcast", year: 2000, genre: "نقش‌آفرینی", emoji: "🌙", desc: "سیستم نبردِ خطیِ شاهکار؛ RPG فراموش‌نشدنی." },
  { id: "rez", name: "رِز", nameEn: "REZ", platform: "dreamcast", year: 2001, genre: "شوتر", emoji: "🎶", desc: "شوترِ موسیقایی؛ هر شلیک، یک نُت؛ سینستزیا." },
  { id: "pso", name: "فانتاسی استار آنلاین", nameEn: "PHANTASY STAR ONLINE", platform: "dreamcast", year: 2000, genre: "نقش‌آفرینی", emoji: "🛰️", desc: "نخستین RPG آنلاینِ کنسول؛ دوستی‌های مجازیِ سال ۲۰۰۰." },
  { id: "power-stone", name: "پاور استون", nameEn: "POWER STONE", platform: "dreamcast", year: 1999, genre: "مبارزه‌ای", emoji: "💎", desc: "مبارزه‌ی آرناییِ شلوغ؛ همه‌چیز سلاح است." },
  { id: "sonic-adventure", name: "سونیک ادونچر", nameEn: "SONIC ADVENTURE", platform: "dreamcast", year: 1998, genre: "پلتفرمر", emoji: "🦔", desc: "سونیکِ سه‌بعدی؛ دریم‌کست با او نفس کشید." },
  { id: "mvc2", name: "مارول در برابر کپ‌کام ۲", nameEn: "MARVEL VS CAPCOM 2", platform: "dreamcast", year: 2000, genre: "مبارزه‌ای", emoji: "🦸", desc: "۵۶ مبارز، سه به سه؛ اوجِ شلوغیِ مبارزه‌ای." },
  /* ── رایانه ── */
  { id: "doom1", name: "دوم", nameEn: "DOOM", platform: "pc", year: 1993, genre: "شوتر", emoji: "😈", desc: "تفنگ‌دارِ بی‌نام روی فوبوس؛ شوتری که دنیا را تسخیر کرد.", note: "روی همه‌چیز پورت شد؛ از ماشین‌حساب تا دستگاه‌های MRI." },
  { id: "doom2", name: "دوم ۲: جهنم روی زمین", nameEn: "DOOM II: HELL ON EARTH", platform: "pc", year: 1994, genre: "شوتر", emoji: "🔥", desc: "شهرها سوختند؛ شاتگانِ دولوله اینجا آمد." },
  { id: "quake1", name: "کویک", nameEn: "QUAKE", platform: "pc", year: 1996, genre: "شوتر", emoji: "⚡", desc: "سه‌بعدیِ واقعی و موسیقیِ ناین اینچ نیلز؛ پدرِ eSport." },
  { id: "warcraft2", name: "وارکرافت ۲", nameEn: "WARCRAFT II", platform: "pc", year: 1995, genre: "استراتژی", emoji: "🛡️", desc: "اردوگاه و اتحاد؛ «Zug zug!» بلیدرلیزارد." },
  { id: "starcraft", name: "استارکرافت", nameEn: "STARCRAFT", platform: "pc", year: 1998, genre: "استراتژی", emoji: "👾", desc: "تران، زرگ و پروتوس؛ ورزشِ ملیِ کره‌ی جنوبی.", note: "در کره مسابقاتش از تلویزیون ملی پخش می‌شد؛ لیگ‌های میلیون‌دلاری." },
  { id: "diablo1", name: "دیابلو", nameEn: "DIABLO", platform: "pc", year: 1996, genre: "نقش‌آفرینی", emoji: "🩸", desc: "تریسترام و زیرزمینِ ۱۶ طبقه؛ «Stay a while and listen»." },
  { id: "diablo2", name: "دیابلو ۲", nameEn: "DIABLO II", platform: "pc", year: 2000, genre: "نقش‌آفرینی", emoji: "💀", desc: "اقلامِ طلایی و بیلدِ شخصیت؛ اعتیادِ خالص." },
  { id: "halflife", name: "هاف‌لایف", nameEn: "HALF-LIFE", platform: "pc", year: 1998, genre: "شوتر", emoji: "🔬", desc: "گوردون فریمن و بلک‌مسا؛ قصه‌گوییِ بی‌کات‌سین.", note: "مادِ کانتر-استرایک از دلش بیرون آمد و دنیا را گرفت." },
  { id: "aoe2", name: "عصر امپراتوری‌ها ۲", nameEn: "AGE OF EMPIRES II", platform: "pc", year: 1999, genre: "استراتژی", emoji: "🏰", desc: "از عصر تاریکی تا امپراتوری؛ «Wololo!»", note: "چهار بار بازسازی شد؛ هنوز آنلاینِ فعال دارد." },
  { id: "red-alert", name: "کامند و کانکر: رد الرت", nameEn: "COMMAND & CONQUER: RED ALERT", platform: "pc", year: 1996, genre: "استراتژی", emoji: "☭", desc: "شوروی در برابر متفقین؛ «Kirov reporting!»" },
  { id: "monkey1", name: "راز جزیره‌ی میمون", nameEn: "THE SECRET OF MONKEY ISLAND", platform: "pc", year: 1990, genre: "ماجراجویی", emoji: "🏴‍☠️", desc: "گایبراش تریپ‌وود؛ طنزِ لوکاس‌آرتز و نبردِ توهین با شمشیر.", note: "«I'm selling these fine leather jackets»؛ معمای فروشندگان مشهور." },
  { id: "civ2", name: "سیویلیزیشن ۲", nameEn: "CIVILIZATION II", platform: "pc", year: 1996, genre: "استراتژی", emoji: "🌍", desc: "«فقط یک نوبتِ دیگر»؛ جمله‌ای که شب‌ها را بلعید." },
  { id: "pop-dos", name: "شاهزاده‌ی ایران (DOS)", nameEn: "PRINCE OF PERSIA (DOS)", platform: "pc", year: 1989, genre: "پلتفرمر", emoji: "⚔️", desc: "۶۰ دقیقه تا نجات پرنسس؛ انیمیشنِ روتوسکوپیِ جردن مکنر.", note: "حرکاتش از برادرِ سازنده فیلم‌برداری شده بود." },
  { id: "wolf3d", name: "ولفنشتاین سه‌بعدی", nameEn: "WOLFENSTEIN 3D", platform: "pc", year: 1992, genre: "شوتر", emoji: "🐺", desc: "پدرِ شوترهای اول‌شخص؛ فرار از قلعه." },
  { id: "duke3d", name: "دوک نوکم ۳دی", nameEn: "DUKE NUKEM 3D", platform: "pc", year: 1996, genre: "شوتر", emoji: "🕶️", desc: "«Hail to the king, baby!»؛ لاس‌وگاس زیرِ حمله." },
  { id: "homm3", name: "هیروز ۳", nameEn: "HEROES OF MIGHT & MAGIC III", platform: "pc", year: 1999, genre: "استراتژی", emoji: "🐉", desc: "نوبتِ تو، نوبتِ من؛ نقشه‌های بی‌پایانِ هات‌سیت.", note: "در ایرانِ دهه‌ی هشتاد، پای ثابتِ همه‌ی مهمانی‌ها بود." },
  { id: "fallout1", name: "فال‌اوت", nameEn: "FALLOUT", platform: "pc", year: 1997, genre: "نقش‌آفرینی", emoji: "☢️", desc: "جنگ هیچ‌وقت عوض نمی‌شود؛ آمریکای پسافاجعه‌ی رترو." },
  { id: "fallout2", name: "فال‌اوت ۲", nameEn: "FALLOUT 2", platform: "pc", year: 1998, genre: "نقش‌آفرینی", emoji: "🏜️", desc: "نوه‌ی والت‌دوِلر؛ آزادیِ انتخابِ بی‌رحم." },
  { id: "baldurs1", name: "بالدرز گیت", nameEn: "BALDUR'S GATE", platform: "pc", year: 1998, genre: "نقش‌آفرینی", emoji: "🧙", desc: "بیوور و فِرُن؛ دانجنز اند درگنزِ واقعی روی رایانه." },
  { id: "myst", name: "میست", nameEn: "MYST", platform: "pc", year: 1993, genre: "ماجراجویی", emoji: "📚", desc: "جزیره‌ی رازآلود و کتاب‌های پرتابی؛ پرفروش‌ترین بازی PC تا ۲۰۰۲." },
  { id: "simcity2000", name: "سیم‌سیتی ۲۰۰۰", nameEn: "SIMCITY 2000", platform: "pc", year: 1993, genre: "شبیه‌ساز", emoji: "🏙️", desc: "شهردار باش؛ بودجه، ترافیک و آرکو (شهر قوسی!)." },
  { id: "sims1", name: "سیمز", nameEn: "THE SIMS", platform: "pc", year: 2000, genre: "شبیه‌ساز", emoji: "🏠", desc: "زندگیِ شبیه‌سازی‌شده؛ استخر را نردبان‌بردار کنید…", note: "پرفروش‌ترین بازی PC تاریخ در زمان خودش؛ میلیون‌ها «سولِسولا»!" },
  { id: "rct1", name: "رولرکوستر تایکون", nameEn: "ROLLERCOASTER TYCOON", platform: "pc", year: 1999, genre: "شبیه‌ساز", emoji: "🎢", desc: "شهربازیِ خودت را بساز؛ دلِ مهمان‌ها را نبر!" },
  { id: "themepark", name: "تِم پارک", nameEn: "THEME PARK", platform: "pc", year: 1994, genre: "شبیه‌ساز", emoji: "🎡", desc: "بستنی‌ها را گران کن، صف‌ها را ببین؛ بول‌فراگ." },
  { id: "lemmings", name: "لمینگ‌ها", nameEn: "LEMMINGS", platform: "pc", year: 1991, genre: "معمایی", emoji: "🐹", desc: "۱۰۰ لمینگ را نجات بده؛ یکی را چتر بده، بقیه دنبال!" },
  { id: "warcraft3", name: "وارکرافت ۳", nameEn: "WARCRAFT III", platform: "pc", year: 2002, genre: "استراتژی", emoji: "🧝", desc: "آرتاس و لیچ‌کینگ؛ قهرمان‌ها آمدند، DOTA زاده شد.", note: "مادِ DOTA از ویرایشگر نقشه‌اش بیرون آمد و ژانرِ موبا ساخت." },
  { id: "cs16", name: "کانتر-استرایک ۱٫۶", nameEn: "COUNTER-STRIKE 1.6", platform: "pc", year: 2000, genre: "شوتر", emoji: "💣", desc: "تروریست یا ضدتروریست؛ «راش بی!» کافه‌نت‌ها.", note: "در کافه‌نت‌های ایران، صدای «Fire in the hole» همه‌جا بود." },
  { id: "max-payne", name: "مکس پین", nameEn: "MAX PAYNE", platform: "pc", year: 2001, genre: "شوتر", emoji: "🕵️", desc: "بولِت‌تایم و کمیک‌نواری؛ انتقام در برفِ نیویورک." },
  { id: "mafia1", name: "مافیا", nameEn: "MAFIA: THE CITY OF LOST HEAVEN", platform: "pc", year: 2002, genre: "اکشن", emoji: "🎩", desc: "تامی آنجلو در دهه‌ی سی؛ گنگستریِ سینمایی." },
  { id: "stronghold", name: "استرانگ‌هولد: جنگ‌های صلیبی", nameEn: "STRONGHOLD: CRUSADER", platform: "pc", year: 2002, genre: "استراتژی", emoji: "🏹", desc: "قلعه بساز، خندق بکن؛ «خورشید!» و حمله‌ی صلیبیون." },
  /* ── ام‌اس‌ایکس ── */
  { id: "metal-gear-msx", name: "متال گیر (MSX)", nameEn: "METAL GEAR (MSX)", platform: "msx", year: 1987, genre: "اکشن", emoji: "📦", desc: "نخستین متال گیر؛ مخفی‌کاری قبل از اینکه مُد شود.", note: "کوجیما ۲۴ ساله بود و سخت‌افزار اجازه‌ی اکشن نمی‌داد؛ پس مخفی‌کاری اختراع شد." },
  { id: "vampire-killer", name: "وampire کیلر", nameEn: "VAMPIRE KILLER", platform: "msx", year: 1986, genre: "پلتفرمر", emoji: "🦇", desc: "کسلوانیای MSX؛ کلید جمع کن تا در باز شود." },
  { id: "knightmare", name: "نایتمِر", nameEn: "KNIGHTMARE", platform: "msx", year: 1986, genre: "شوتر", emoji: "🏹", desc: "پوپولون و شمشیرِ جادویی؛ شوترِ عمودیِ کونامی." },
  { id: "nemesis-msx", name: "نمسیس", nameEn: "NEMESIS (GRADIUS MSX)", platform: "msx", year: 1986, genre: "شوتر", emoji: "🛸", desc: "گرادیوسِ خانگی؛ آپشن‌ها و موج‌های بیکر." },
  { id: "kings-valley", name: "کینگز ولی", nameEn: "KING'S VALLEY", platform: "msx", year: 1985, genre: "معمایی", emoji: "⚱️", desc: "هرم و مومیایی‌ها؛ پازل-پلتفرمرِ کونامی." },
  { id: "galious", name: "هزارتوی گالیوس", nameEn: "KNIGHTMARE II: THE MAZE OF GALIOUS", platform: "msx", year: 1987, genre: "ماجراجویی", emoji: "🏰", desc: "قلعه‌ی بی‌پایانِ مترویدوانیا-مانند؛ بزرگ‌ترین نقشه‌ی MSX." },
  /* ── آمیگا ── */
  { id: "another-world", name: "جهانی دیگر", nameEn: "ANOTHER WORLD", platform: "amiga", year: 1991, genre: "ماجراجویی", emoji: "🌌", desc: "لستر در سیاره‌ی بیگانه؛ سینمای تعاملیِ اریک شاهی.", note: "تنها، در دو سال و با یک نرم‌افزار خانگی ساخته شد." },
  { id: "speedball2", name: "اسپیدبال ۲", nameEn: "SPEEDBALL 2", platform: "amiga", year: 1990, genre: "ورزشی", emoji: "🤾", desc: "هندبالِ سایبرپانک؛ «Ice cream!» فروشنده‌ی معروف." },
  { id: "cannon-fodder", name: "کانون فادر", nameEn: "CANNON FODDER", platform: "amiga", year: 1993, genre: "استراتژی", emoji: "🪖", desc: "سربازهای کوچکِ قربانی؛ طنزِ سیاهِ سنسی‌بل." },
  { id: "sensible-soccer", name: "سنسیبل ساکر", nameEn: "SENSIBLE SOCCER", platform: "amiga", year: 1992, genre: "ورزشی", emoji: "⚽", desc: "فوتبالِ ریز از بالا؛ گل‌های قوسیِ ابدی." },
  { id: "shadow-beast", name: "شدو آو د بیست", nameEn: "SHADOW OF THE BEAST", platform: "amiga", year: 1989, genre: "پلتفرمر", emoji: "🐗", desc: "گرافیکِ ۱۲ لایه‌ی پارالاکس؛ نمایشِ قدرتِ آمیگا." },
  { id: "turrican2", name: "توریکان ۲", nameEn: "TURRICAN II", platform: "amiga", year: 1991, genre: "شوتر", emoji: "🦾", desc: "زره‌ی متحول‌شو؛ موسیقیِ کریس هیلسبک افسانه است." },
  { id: "worms1", name: "ورمز", nameEn: "WORMS", platform: "amiga", year: 1995, genre: "استراتژی", emoji: "🪱", desc: "کرم‌های جنگجو با بزوکا؛ «Grenade!» و خنده." },
  { id: "flashback", name: "فلش‌بک", nameEn: "FLASHBACK", platform: "amiga", year: 1992, genre: "ماجراجویی", emoji: "🔫", desc: "کنراد و خاطراتِ پاک‌شده؛ روتوسکوپیِ علمی‌تخیلی." },
  /* ── سگا ساترن ── */
  { id: "nights", name: "نایتس اینتو دریمز", nameEn: "NIGHTS INTO DREAMS", platform: "saturn", year: 1996, genre: "پلتفرمر", emoji: "🃏", desc: "دلقکِ رؤیاها و پروازِ بی‌پایان؛ جادوی سونیک‌تیم." },
  { id: "vf2", name: "ویرچوا فایتر ۲", nameEn: "VIRTUA FIGHTER 2", platform: "saturn", year: 1995, genre: "مبارزه‌ای", emoji: "🥋", desc: "۶۰ فریمِ واقعی؛ دقیق‌ترین مبارزه‌ی سه‌بعدی زمانش." },
  { id: "panzer-saga", name: "پانزر دراگون ساگا", nameEn: "PANZER DRAGOON SAGA", platform: "saturn", year: 1998, genre: "نقش‌آفرینی", emoji: "🐉", desc: "سوار بر اژدها؛ کمیاب‌ترین RPG تاریخ.", note: "چاپش محدود بود؛ نسخه‌ی سالمش هزاران دلار می‌ارزد." },
  { id: "radiant-silvergun", name: "رادیانت سیلورگان", nameEn: "RADIANT SILVERGUN", platform: "saturn", year: 1998, genre: "شوتر", emoji: "🔺", desc: "هفت سلاح، بدون پاورآپ؛ شاهکارِ تِرژر." },
  { id: "guardian-heroes", name: "گاردین هیروز", nameEn: "GUARDIAN HEROES", platform: "saturn", year: 1996, genre: "اکشن", emoji: "⚔️", desc: "بزن‌بهادرِ نقش‌آفرینی؛ شش بازیکن همزمان!" },
  /* ── گیم‌بوی ادونس ── */
  { id: "pokemon-ruby", name: "پوکمون روبی/سافایر", nameEn: "POKÉMON RUBY / SAPPHIRE", platform: "gba", year: 2002, genre: "نقش‌آفرینی", emoji: "🔴", desc: "هون؛ مسابقه‌های پوکمون و نبردِ دوگانه." },
  { id: "metroid-fusion", name: "متروید فیوژن", nameEn: "METROID FUSION", platform: "gba", year: 2002, genre: "ماجراجویی", emoji: "🧫", desc: "ساموسِ آلوده و SA-X؛ تعقیب‌وگریزِ وحشتناک." },
  { id: "minish-cap", name: "زلدا: کلاه مینیش", nameEn: "ZELDA: THE MINISH CAP", platform: "gba", year: 2004, genre: "ماجراجویی", emoji: "🍃", desc: "دنیای زیرِ پایت؛ وقتی اندازه‌ات به‌اندازه‌ی مورچه است." },
  { id: "marioluigi-ss", name: "ماریو و لوئیجی: سوپراستار ساگا", nameEn: "MARIO & LUIGI: SUPERSTAR SAGA", platform: "gba", year: 2003, genre: "نقش‌آفرینی", emoji: "⚡", desc: "دو برادر و لوبیای خنده؛ RPG-اکشنِ هوشمند." },
  { id: "fire-emblem", name: "فایر امبلم", nameEn: "FIRE EMBLEM (GBA)", platform: "gba", year: 2003, genre: "استراتژی", emoji: "🛡️", desc: "استراتژیِ نوبتی که مرگش دائمی است؛ دل ببند و نترس!" },
  { id: "advance-wars", name: "ادونس وارز", nameEn: "ADVANCE WARS", platform: "gba", year: 2001, genre: "استراتژی", emoji: "🎖️", desc: "جنگِ کارتونیِ عمیق؛ فرمانده و نقشه‌ی شطرنجی." },
  { id: "golden-sun", name: "گلدن سان", nameEn: "GOLDEN SUN", platform: "gba", year: 2001, genre: "نقش‌آفرینی", emoji: "☀️", desc: "جادوی سایکینری؛ بهترین گرافیکِ GBA." },
  { id: "castlevania-aos", name: "کسلوانیا: آریا آو سورو", nameEn: "CASTLEVANIA: ARIA OF SORROW", platform: "gba", year: 2003, genre: "نقش‌آفرینی", emoji: "🌘", desc: "سوما و قدرتِ روح‌ها؛ مترویدوانیای جیبیِ بی‌نقص." },
  { id: "mother3", name: "مادر ۳", nameEn: "MOTHER 3", platform: "gba", year: 2006, genre: "نقش‌آفرینی", emoji: "🌻", desc: "لوکاس و جزیره‌ی نوور؛ گریه‌دارترین RPG ژاپن.", note: "هیچ‌وقت رسماً از ژاپن خارج نشد؛ ترجمه‌ی هواداری‌اش افسانه است." },
  { id: "warioware", name: "واریوور", nameEn: "WARIOWARE", platform: "gba", year: 2003, genre: "معمایی", emoji: "⚡", desc: "میکروگیم‌های پنج‌ثانیه‌ای؛ دیوانگیِ خالصِ نینتندو." },
  /* ── گیم گیر ── */
  { id: "sonic-gg", name: "سونیک (گیم گیر)", nameEn: "SONIC (GAME GEAR)", platform: "gamegear", year: 1991, genre: "پلتفرمر", emoji: "🦔", desc: "سونیکِ رنگیِ جیبی؛ باتری‌ها فدا شدند." },
  { id: "shining-gg", name: "شینینگ فورس: شمشیر هاجیا", nameEn: "SHINING FORCE: SWORD OF HAJYA", platform: "gamegear", year: 1994, genre: "استراتژی", emoji: "⚔️", desc: "استراتژیِ نوبتیِ جیبی؛ انحصاریِ محبوب گیم گیر." },
  { id: "columns-gg", name: "کالمز", nameEn: "COLUMNS (GAME GEAR)", platform: "gamegear", year: 1990, genre: "معمایی", emoji: "💎", desc: "جواهرهای سه‌تایی؛ تتریسِ رنگیِ سگا." },
  { id: "sor-gg", name: "شورش در شهر (گیم گیر)", nameEn: "STREETS OF RAGE (GG)", platform: "gamegear", year: 1992, genre: "اکشن", emoji: "👊", desc: "شهرِ فاسد در جیب؛ اکسل و بلیزِ کوچک." },

  /* ── سگا مستر سیستم ── */
  { id: "alex-kidd", name: "الکس کید در سرزمین معجزه", nameEn: "ALEX KIDD IN MIRACLE WORLD", platform: "sms", year: 1986, genre: "پلتفرمر", emoji: "🧒", desc: "ماستِ سگای پیش از سونیک؛ پسرکی که با مشت، سنگ را خرد می‌کرد.", note: "در بعضی کشورها بازی داخلِ خودِ کنسول بود؛ نخستین خاطره‌ی میلیون‌ها بچه." },
  { id: "wonder-boy", name: "واندر بوی", nameEn: "WONDER BOY", platform: "sms", year: 1986, genre: "پلتفرمر", emoji: "🛹", desc: "پسری با تَبَر و اسکیت؛ میوه‌ها را بگیر وگرنه جانت آب می‌شود." },
  { id: "fantasy-zone", name: "فانتزی زون", nameEn: "FANTASY ZONE", platform: "sms", year: 1986, genre: "شوتر", emoji: "🎈", desc: "سفینه‌ی بالدار در سیاره‌های رنگی؛ شوتری که لبخند می‌زد و می‌کشت." },
  { id: "psycho-fox", name: "سایکو فاکس", nameEn: "PSYCHO FOX", platform: "sms", year: 1989, genre: "پلتفرمر", emoji: "🦊", desc: "روباهی که گرگ و پرنده می‌شد؛ پرش‌هایش هنوز خواب شب خیلی‌هاست." },
  { id: "wonder-boy-3", name: "واندر بوی ۳: تله‌ی اژدها", nameEn: "WONDER BOY III: THE DRAGON'S TRAP", platform: "sms", year: 1989, genre: "ماجراجویی", emoji: "🐉", desc: "هر بار که می‌میری، حیوان تازه‌ای می‌شدی؛ مترویدوانیای ۸ بیتی." },
  { id: "phantasy-star", name: "فانتزی استار", nameEn: "PHANTASY STAR", platform: "sms", year: 1987, genre: "نقش‌آفرینی", emoji: "🪐", desc: "آلیس و انتقامش در منظومه‌ی آلگول؛ جدّ همه‌ی RPGهای سگا.", note: "نخستین RPG کنسولی با سیاه‌چال‌های سه‌بعدیِ اول‌شخص." },
  { id: "r-type-sms", name: "آر-تایپ", nameEn: "R-TYPE", platform: "sms", year: 1988, genre: "شوتر", emoji: "🚀", desc: "سفینه‌ی R-9 و گویِ Force؛ شوتری که صبر را تمرین می‌داد." },
  { id: "ghost-house", name: "خانه‌ی ارواح", nameEn: "GHOST HOUSE", platform: "sms", year: 1986, genre: "پلتفرمر", emoji: "👻", desc: "میکی در عمارت خون‌آشام؛ چراغ‌ها را روشن کن و درها را بکوب.", note: "یکی از اولین انحصاری‌های مستر سیستم؛ شمعدان‌هایش معروف‌اند." },
  { id: "aztec-adventure", name: "ماجراجویی آزتک", nameEn: "AZTEC ADVENTURE", platform: "sms", year: 1987, genre: "اکشن", emoji: "🗿", desc: "نینی در معبد آزتک؛ سکوهایی که از نمای بالا گول می‌زدند." },

  /* ── مگا درایو؛ موج دوم شاهکارهای سگا ── */
  { id: "streets-of-rage", name: "شورش در شهر", nameEn: "STREETS OF RAGE", platform: "megadrive", year: 1991, genre: "اکشن", emoji: "🥊", desc: "اکسل، بلیز و آدام در خیابان‌های فاسد؛ شروع سه‌گانه‌ای که گیم‌نت‌های ایران را ساخت.", note: "پاسخ سگا به فاینال فایت؛ موسیقی‌اش زیر پای هر دعوایی بود." },
  { id: "streets-of-rage-2", name: "شورش در شهر ۲", nameEn: "STREETS OF RAGE II", platform: "megadrive", year: 1992, genre: "اکشن", emoji: "🥊", desc: "اسکیت و مکس آمدند؛ بسیاری هنوز آن را بهترین بزن‌بهادرِ تاریخ می‌دانند.", note: "موسیقی الکترونیک یوزو کوشیرو در ۱۹۹۲ از موسیقی کلاب‌های زمانش جلوتر بود." },
  { id: "streets-of-rage-3", name: "شورش در شهر ۳", nameEn: "STREETS OF RAGE III", platform: "megadrive", year: 1994, genre: "اکشن", emoji: "🥊", desc: "رباتها، کانگوروی مشت‌زن و پایان‌های چندگانه؛ خداحافظیِ پرآتش سه‌گانه." },
  { id: "golden-axe-2", name: "تبر طلایی ۲", nameEn: "GOLDEN AXE II", platform: "megadrive", year: 1991, genre: "اکشن", emoji: "🪓", desc: "بازگشت بربر و آمازون؛ جادوی آبی و اژدهای سبز، یک‌بار دیگر." },
  { id: "golden-axe-3", name: "تبر طلایی ۳", nameEn: "GOLDEN AXE III", platform: "megadrive", year: 1993, genre: "اکشن", emoji: "🪓", desc: "مسیرهای شعبه‌شده و قهرمانان تازه؛ ژاپن دید و جهان سال‌ها بعد.", note: "در غرب فقط از راه سگا چنل پخش شد؛ نسخه‌ی ژاپنی‌اش گنجینه‌ی کلکسیونرهاست." },
  { id: "revenge-of-shinobi", name: "انتقام شینوبی", nameEn: "THE REVENGE OF SHINOBI", platform: "megadrive", year: 1989, genre: "اکشن", emoji: "🥷", desc: "جو موساشی در برابر نئو-زید؛ شوریکن‌هایی که با موسیقی کوشیرو پرتاب می‌شدند.", note: "باس‌هایش تقلید شخصیت‌های معروف بود؛ سگا بعدها مجبور شد چندتایش را عوض کند." },
  { id: "comix-zone", name: "منطقه‌ی کمیک", nameEn: "COMIX ZONE", platform: "megadrive", year: 1995, genre: "اکشن", emoji: "💥", desc: "ترنر داخل کمیکِ خودش گیر کرد؛ هر پنل، یک مرحله‌ی جنگ.", note: "حرف‌زدنِ شخصیت‌ها با حبابِ گفتار؛ در ۱۹۹۵ از خیلی چیزها جلوتر بود." },
  { id: "ristar", name: "ریستار", nameEn: "RISTAR", platform: "megadrive", year: 1995, genre: "پلتفرمر", emoji: "⭐", desc: "ستاره‌ای که با دست‌های کشسانش از کهکشان آویزان می‌شد؛ دیر آمد و ماندگار شد." },
  { id: "earthworm-jim", name: "جیم کرم خاکی", nameEn: "EARTHWORM JIM", platform: "megadrive", year: 1994, genre: "پلتفرمر", emoji: "🪱", desc: "کرم خاکی در لباس فضایی؛ شوخی‌ای که از هر کارتونِ زمانش بامزه‌تر بود.", note: "مرحله‌ی «گاوها با شتاب می‌افتند» از مشهورترین لحظه‌های تاریخ بازی است." },
  { id: "gunstar-heroes", name: "قهرمانان گان‌استار", nameEn: "GUNSTAR HEROES", platform: "megadrive", year: 1993, genre: "شوتر", emoji: "🔫", desc: "اولین ساخته‌ی استودیوی ترژر؛ تفنگ‌های ترکیبی و انفجارِ بی‌وقفه.", note: "دونفره‌ی همکاری‌اش استانداردِ اکشنِ دونفره شد؛ هنوز هم بازی می‌شود." },
  { id: "kid-chameleon", name: "کید آفتاب‌پرست", nameEn: "KID CHAMELEON", platform: "megadrive", year: 1992, genre: "پلتفرمر", emoji: "🦎", desc: "کلاه‌خودی که ده شخصیت می‌شد؛ صد مرحله و هیچ ذخیره‌ای؛ شجاعتِ خالص." },
  { id: "columns-md", name: "ستون‌ها", nameEn: "COLUMNS", platform: "megadrive", year: 1990, genre: "معمایی", emoji: "💎", desc: "جواهرهایی که سه‌تا سه‌تا می‌درخشیدند؛ جواب سگا به تتریس.", note: "بازیِ همراهِ خیلی از مگا درایوها؛ ملودی‌اش را همه می‌شناسند." },
  { id: "mean-bean", name: "ماشین لوبیای دکتر رباتنیک", nameEn: "DR. ROBOTNIK'S MEAN BEAN MACHINE", platform: "megadrive", year: 1993, genre: "معمایی", emoji: "🫘", desc: "لوبیاهای رنگیِ پازلی با صورت‌های خندان دشمن؛ پویو برای غربی‌ها." },
  { id: "shining-force-2", name: "شینینگ فورس ۲", nameEn: "SHINING FORCE II", platform: "megadrive", year: 1993, genre: "نقش‌آفرینی", emoji: "⚔️", desc: "جنگ‌های شطرنجی با شمشیر و جادو؛ استراتژیِ نوبتیِ خوش‌دستِ سگا." },
  { id: "landstalker", name: "لنداستالکر", nameEn: "LANDSTALKER", platform: "megadrive", year: 1992, genre: "ماجراجویی", emoji: "🗺️", desc: "نایجل و پریِ کوچک در جزیره‌ی گنج؛ ایزومتریکِ ماجراجویانه.", note: "پرش‌های ایزومتریک‌اش بازیکن را دیوانه می‌کرد؛ ولی شهرهایش زنده بود." },
  { id: "toejam-earl", name: "توجَم و ارل", nameEn: "TOEJAM & EARL", platform: "megadrive", year: 1991, genre: "ماجراجویی", emoji: "🎷", desc: "دو فضاییِ فانک دنبال تکه‌های سفینه؛ دونفره‌ای که نقشه نداشت!", note: "موسیقی فانکش هنوز سمپل می‌شود؛ کفش‌های موشکی‌اش افسانه‌اند." },
  { id: "eternal-champions", name: "قهرمانان ابدی", nameEn: "ETERNAL CHAMPIONS", platform: "megadrive", year: 1993, genre: "مبارزه‌ای", emoji: "🏛️", desc: "مبارزانی که قبل از مرگشان ربوده شدند تا دوباره بجنگند؛ خشونتِ سینمایی.", note: "پایان‌های «سینمایی‌مرگ» هر شخصیت، تماشاچی جمع می‌کرد." },
  { id: "contra-hard-corps", name: "کنترا: هارد کورپس", nameEn: "CONTRA: HARD CORPS", platform: "megadrive", year: 1994, genre: "شوتر", emoji: "🪖", desc: "کنترا با ربات و گرگینه؛ پایان‌های چندگانه و انتخاب مسیر." },
  { id: "castlevania-bloodlines", name: "کسلوانیا: خون‌بها", nameEn: "CASTLEVANIA: BLOODLINES", platform: "megadrive", year: 1994, genre: "اکشن", emoji: "🧛", desc: "شلاقِ کونامی روی سگا؛ دو شکارچی، اروپای جنگ‌زده و خون‌آشام‌ها." },
  { id: "battletoads-md", name: "بتل‌تودز", nameEn: "BATTLETOADS", platform: "megadrive", year: 1993, genre: "اکشن", emoji: "🐸", desc: "وزغ‌های خشمگین با مشت‌های غول‌پیکر؛ سختی‌ای که دوستش داشتیم.", note: "مرحله‌ی Turbo Tunnel از معروف‌ترین مرحله‌های سختِ تاریخ است." },
  { id: "rocket-knight", name: "راکت نایت ادونچرز", nameEn: "ROCKET KNIGHT ADVENTURES", platform: "megadrive", year: 1993, genre: "پلتفرمر", emoji: "🚀", desc: "صاری‌ای با راکت‌پشتی؛ شوالیه‌ای که روی ریل می‌دوید." },
  { id: "alien-soldier", name: "الین سولجر", nameEn: "ALIEN SOLDIER", platform: "megadrive", year: 1995, genre: "اکشن", emoji: "👽", desc: "باز هم ترژر؛ از ثانیه‌ی اول بوس‌راش، بی‌وقفه تا آخر.", note: "در ژاپن و اروپا روی کارتریج آمد؛ آمریکایی‌ها سال‌ها حسرتش را خوردند." },
  { id: "thunder-force-4", name: "تاندرفورس ۴", nameEn: "THUNDER FORCE IV", platform: "megadrive", year: 1992, genre: "شوتر", emoji: "⚡", desc: "طوفانِ فضایی؛ شوتری که مگا درایو را تا مرز توانش می‌راند." },
  { id: "virtua-racing", name: "ویرچوا ریسینگ", nameEn: "VIRTUA RACING", platform: "megadrive", year: 1993, genre: "مسابقه‌ای", emoji: "🏎️", desc: "اولین بازی پلی‌گانِ سه‌بعدیِ خانگی؛ فرمول یکِ سگا روی کارتریج.", note: "تراشه‌ی SVP داخل کارتریج بود؛ قیمتش دو برابر بازی‌های معمولی بود." },
  { id: "sparkster", name: "اسپارکستر", nameEn: "SPARKSTER", platform: "megadrive", year: 1994, genre: "پلتفرمر", emoji: "✨", desc: "اپوسومی با شمشیر و راکت؛ سرعتی که چشم را جا می‌گذاشت." },
  { id: "bonanza-bros", name: "بونانزا بروز", nameEn: "BONANZA BROS.", platform: "megadrive", year: 1991, genre: "اکشن", emoji: "💰", desc: "دو دزدِ دست‌وپا‌چلفتی که پشت مبل‌ها قایم می‌شدند؛ دونفره‌ی خنده‌دار." },
  { id: "shadow-dancer", name: "شدو دنسر", nameEn: "SHADOW DANCER", platform: "megadrive", year: 1990, genre: "اکشن", emoji: "🌑", desc: "شینوبی و سگِ سفیدش؛ سایه‌ها و شوریکن‌ها در شهر نئون.", note: "سگش «یاماتو» خودش یک سلاح بود؛ حمله‌ی شیرجه‌اش معروف است." },
  { id: "gain-ground", name: "گین‌گراند", nameEn: "GAIN GROUND", platform: "megadrive", year: 1990, genre: "استراتژی", emoji: "🏹", desc: "هر مرحله، سه قهرمان و یک فکر؛ ترکیبِ عجیبِ استراتژی و اکشنِ سگا." },
  { id: "mega-man-wily", name: "مگامن: جنگ‌های وایلی", nameEn: "MEGA MAN: THE WILY WARS", platform: "megadrive", year: 1994, genre: "پلتفرمر", emoji: "⚙️", desc: "سه مگامنِ کلاسیک در یک کارتریج؛ کپ‌کام روی زمینِ سگا.", note: "در آمریکا فقط به مشترکان سگا چنل رسید؛ کمیاب‌ترین مگامنِ فیزیکی." },
  { id: "beyond-oasis", name: "فراسوی اوآسیس", nameEn: "BEYOND OASIS", platform: "megadrive", year: 1994, genre: "نقش‌آفرینی", emoji: "🌴", desc: "انگشتری که جن‌ها را صدا می‌زد؛ زلدایِ سگا که کسی جدی‌اش نگرفت.", note: "اروپایی‌ها با نام The Story of Thor می‌شناسندش؛ گرافیکش هنوز چشم‌نواز است." },
  { id: "dune-2-md", name: "دیون ۲", nameEn: "DUNE II", platform: "megadrive", year: 1993, genre: "استراتژی", emoji: "🏜️", desc: "ادویه باید جریان یابد؛ پدرِ استراتژیِ هم‌زمان روی کنسول." },
  { id: "sonic-spinball", name: "سونیک اسپین‌بال", nameEn: "SONIC SPINBALL", platform: "megadrive", year: 1993, genre: "اکشن", emoji: "🎱", desc: "سونیک خودش توپِ پین‌بال شد؛ عجیب، سخت و وسوسه‌کننده." },

  /* ── آرکیدهای سگا ── */
  { id: "space-harrier", name: "اسپیس هاریر", nameEn: "SPACE HARRIER", platform: "arcade", year: 1985, genre: "شوتر", emoji: "🛩️", desc: "مردی که روی موشک می‌دوید؛ اولین شگفتیِ «سوپر اسکیلر» سگا.", note: "افکتِ پرسپکتیوش بدون هیچ سخت‌افزار سه‌بعدی‌ای ساخته شده بود." },
  { id: "hang-on", name: "هنگ‌آن", nameEn: "HANG-ON", platform: "arcade", year: 1985, genre: "مسابقه‌ای", emoji: "🏍️", desc: "کابینتی که خودِ موتور بود؛ باید روی پیچ‌ها کج می‌شدی.", note: "اولین کابینتِ حرکتیِ تمام‌عیار؛ صفش از درِ گیم‌نت بیرون می‌زد." },
  { id: "after-burner-2", name: "افتر برنر ۲", nameEn: "AFTER BURNER II", platform: "arcade", year: 1987, genre: "شوتر", emoji: "✈️", desc: "F-14 و آسمانی پر از موشک؛ کابینتِ چرخانِ سرگیجه‌آور.", note: "نسخه‌ی کابینت، خلبان را با صندلی می‌چرخاند؛ گران‌ترین تجربه‌ی آرکید زمانش." },
  { id: "daytona-usa", name: "دیتونا یو‌اس‌ای", nameEn: "DAYTONA USA", platform: "arcade", year: 1994, genre: "مسابقه‌ای", emoji: "🚥", desc: "«LET'S GO AWAY!» و استارتِ غلتان؛ ستونِ گیم‌نت‌های ایران در دهه‌ی هفتاد.", note: "آهنگش را یوزو کوشیرو ننوشت اما همه زیر لب خواندندش؛ هشت‌نفره‌ی لینک‌شده‌اش افسانه بود." },
  { id: "sega-rally", name: "سگا رالی", nameEn: "SEGA RALLY CHAMPIONSHIP", platform: "arcade", year: 1995, genre: "مسابقه‌ای", emoji: "🚙", desc: "خاک، گِل و دریفت؛ فیزیکِ رالی‌اش هنوز الگوی بازی‌های ماشین است.", note: "سلوپِ خاک زیرِ چرخ‌ها را ۱۹۹۵ شبیه‌سازی کرد؛ منتقدها هنوز تعریفش می‌کنند." },
  { id: "super-monaco-gp", name: "سوپر موناکو جی‌پی", nameEn: "SUPER MONACO GP", platform: "arcade", year: 1989, genre: "مسابقه‌ای", emoji: "🏆", desc: "فرمول یک در تونل موناکو؛ آیرتون سنا مشاورش بود.", note: "نسخه‌ی خانگی‌اش را خودِ سنا تنظیم کرد؛ جایزه‌ی بردنش هم مسابقه با سنا بود." },
  { id: "virtua-cop", name: "ویرچوا کاپ", nameEn: "VIRTUA COP", platform: "arcade", year: 1994, genre: "شوتر", emoji: "🚓", desc: "تفنگِ نوری و «عدالتِ» سریع؛ پلیس‌بازیِ رسمیِ گیم‌نت‌ها.", note: "ژستِ خشاب‌گذاشتنِ تفنگش را همه‌ی بچه‌ها تقلید می‌کردند." },
  { id: "alien-syndrome", name: "الین سیندروم", nameEn: "ALIEN SYNDROME", platform: "arcade", year: 1987, genre: "شوتر", emoji: "🧬", desc: "نجاتِ گروگان‌ها پیش از انفجار سفینه؛ دونفره‌ی پُراسترسِ سگا.", note: "شمارش معکوسِ هر مرحله، ضربان را به صدای بازی وصل می‌کرد." },
  { id: "super-hang-on", name: "سوپر هنگ‌آن", nameEn: "SUPER HANG-ON", platform: "arcade", year: 1987, genre: "مسابقه‌ای", emoji: "🛣️", desc: "موتورِ سگا با توربو؛ مسیرهای شعبه‌شده و سرعتِ جنون.", note: "در گینس به‌عنوان یکی از بازی‌های پرفروش آرکیدِ ژاپن ثبت شده." },
  { id: "power-drift", name: "پاور دریفت", nameEn: "POWER DRIFT", platform: "arcade", year: 1988, genre: "مسابقه‌ای", emoji: "🎢", desc: "پیست‌های ترن‌هواییِ معلق؛ اسپرایت‌های سگا در اوجِ نمایش.", note: "کابینتِ تکانش طوری بود که خیلی‌ها فقط برای سواری‌اش سکه می‌انداختند." },
];

/* ---------- ابزار جستجو ---------- */
export const searchGames = (q: string): Game[] => {
  const s = q.trim().toLowerCase();
  if (!s) return [];
  return GAMES.filter(
    (g) =>
      g.name.includes(q.trim()) ||
      g.nameEn.toLowerCase().includes(s) ||
      g.genre.includes(q.trim())
  );
};
